### ISSUE TITLE
ruleengine error AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by dove-young** [StackStorm/st2#5000] opened 2020-07-21 08:47 UTC
## SUMMARY

Provide a quick summary of your bug report.

Run `linux.FileWatchSensor`,  found error in `st2rulesengine` log messages

```
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,473 ERROR [-] Logged from file filter.py, line 72
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: {'description': u'Sample rule firing on action completion.', 'tags': [], 'ref': u'examples.sample_rule_with_actiontrigger', 'enabled': True, 'name': u'sample_rule_with_actiontrigger', 'trigger': u'core.st2.generic.actiontrigger', 'metadata_file': u'rules/sample_rule_with_actiontrigger.yaml', 'context': {}, 'criteria': {u'trigger.action_name': {u'pattern': u'local', u'type': u'equals'}, u'trigger.status': {u'pattern': u'error', u'type': u'equals'}}, 'action': 'ActionExecutionSpecDB@139967902342736(ref="core.local", parameters="{u\'cmd\': u\'echo "{{trigger.start_timestamp}}"\'}")', 'pack': u'examples', 'type': 'RuleTypeSpecDB@139967902340176(ref="standard", parameters="{}")', 'id': '5f0ff28cc8f628708f869b8f', 'uid': u'rule:examples:sample_rule_with_actiontrigger'}
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: <type 'dict'>
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: ActionExecutionSpecDB@139967902342736(ref="core.local", parameters="{u'cmd': u'echo "{{trigger.start_timestamp}}"'}")
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: <type 'str'>
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,474 ERROR [-] Traceback (most recent call last):
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,475 ERROR [-]   File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,475 ERROR [-]     msg = self.format(record)
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,476 ERROR [-]   File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,476 ERROR [-]     return fmt.format(record)
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,476 ERROR [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 176, in format
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,476 ERROR [-]     attributes = self._format_extra_attributes(attributes=attributes)
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,476 ERROR [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 151, in _format_extra_attributes
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,476 ERROR [-]     value = serialize_object(obj=value)
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,477 ERROR [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 65, in serialize_object
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,477 ERROR [-]     value = obj.to_serializable_dict(mask_secrets=True)
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,477 ERROR [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/stormbase.py", line 105, in to_serializable_dict
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,477 ERROR [-]     serializable_dict = self.mask_secrets(value=serializable_dict)
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,477 ERROR [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/rule.py", line 127, in mask_secrets
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,477 ERROR [-]     action_ref = result.get('action', {}).get('ref', None)
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,478 ERROR [-] AttributeError: 'str' object has no attribute 'get'
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,478 ERROR [-] Logged from file filter.py, line 72
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,507 INFO [-] 0 rule(s) found to enforce for st2.generic.actiontrigger.
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,508 INFO [-] Matched 0 rule(s) for trigger_instance 5f16a98d3dbdecc0066057d7 (trigger=core.st2.generic.actiontrigger)
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,508 INFO [-] No matching rules found for trigger instance 5f16a98d3dbdecc0066057d7.

```

### STACKSTORM VERSION

Paste the output of ``st2 --version``:

st2 3.2.0, on Python 2.7.5

##### OS, environment, install method

Post what OS you are running this on, along with any other relevant information/

- RHEL 7.6 
- ansible-st2 install

## Steps to reproduce the problem

Show how to reproduce the problem, using a minimal test-case. Make sure to include any content
(pack content - workflows, actions, etc.) which are needed to reproduce the problem.

- install example pack
- start sensor `linux.FileWatchSensor`
```
/opt/stackstorm/st2/bin/st2sensorcontainer --config-file=/etc/st2/st2.conf --sensor-ref=linux.FileWatchSensor
```
- add content to `/tmp/st2_test`
```
echo vault-server-help.txt | tee -a /tmp/st2_test
```
- check ruleengine log 
```
journalctl -xel --no-page -f -u   st2rulesengine
```
- found error

## Expected Results

What did you expect to happen when running the steps above?

## Actual Results

when add debug info in `/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/rule.py`, found the `type(result.get('action', {}))` is actually a string 

```
122         print(result)
123         print(type(result))
124         print(result.get('action', {}))
125         print(type(result.get('action', {})))
126
```

```
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: 2020-07-21 01:38:37,473 ERROR [-] Logged from file filter.py, line 72
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: {'description': u'Sample rule firing on action completion.', 'tags': [], 'ref': u'examples.sample_rule_with_actiontrigger', 'enabl
ed': True, 'name': u'sample_rule_with_actiontrigger', 'trigger': u'core.st2.generic.actiontrigger', 'metadata_file': u'rules/sample_rule_with_actiontrigger.yaml', 'context': {}, 'criteria': {u'trigger.a
ction_name': {u'pattern': u'local', u'type': u'equals'}, u'trigger.status': {u'pattern': u'error', u'type': u'equals'}}, 'action': 'ActionExecutionSpecDB@139967902342736(ref="core.local", parameters="{u
\'cmd\': u\'echo "{{trigger.start_timestamp}}"\'}")', 'pack': u'examples', 'type': 'RuleTypeSpecDB@139967902340176(ref="standard", parameters="{}")', 'id': '5f0ff28cc8f628708f869b8f', 'uid': u'rule:exam
ples:sample_rule_with_actiontrigger'}
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: <type 'dict'>
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: ActionExecutionSpecDB@139967902342736(ref="core.local", parameters="{u'cmd': u'echo "{{trigger.start_timestamp}}"'}")
Jul 21 01:38:37 agentavtone-worker2.fyre.ibm.com st2rulesengine[11798]: <type 'str'>
```

What happened? What output did you get?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by nmaludy** [comment] 2020-07-21 12:14
Duplicate of #4934

Closed by #4952

**Closed by nmaludy** 2020-07-21 12:14 UTC
Labels: status:to be verified

**Comment by nmaludy** [comment] 2020-07-21 13:18
@dove-young FYI #4952 was just merged into master

**Comment by armab** [comment] 2020-07-21 23:46
Thanks @nmaludy!
