### ISSUE TITLE
Killing/Stopping action runner processes while executing mistral workflow causes workflow to be stuck in "running" state.

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#3441] opened 2017-06-01 01:38 UTC
https://github.com/StackStorm/st2/pull/3412/files doesn't appear to fix the issue. 

Repro instructions and logs here
https://gist.github.com/lakshmi-kannan/e5f60c3125dfb01251a6fc305a6d8ea5

**Comment by m4dcoder** [comment] 2017-06-01 01:51
What's the corresponding workflow execution status in mistral? What's the status of st2resultstracker?

**Comment by m4dcoder** [comment] 2017-06-01 01:58
Also, please drill down into the st2 action execution and report back if any children is abandoned?  The fix from PR 3412 is triggered when a child action execution is being abandoned on worker shutdown.

**Comment by m4dcoder** [comment] 2017-06-01 18:48
I'm not able to reproduce this. I assumed you waited at least 20s for st2resultstracker to pick up the result.

```
vagrant@metropolis:~$ st2 run core.local "sleep 300" -a
To get the results, execute:
 st2 execution get 593060ee1e6c3a707c8057b8
vagrant@metropolis:~$ st2 run examples.mistral-basic "sleep 300" -a
To get the results, execute:
 st2 execution get 593060f41e6c3a707c8057bb
vagrant@metropolis:~$ st2 execution list
+----------------------------+-----------------+--------------+-------------------------+-----------------+---------------+
| id                         | action.ref      | context.user | status                  | start_timestamp | end_timestamp |
+----------------------------+-----------------+--------------+-------------------------+-----------------+---------------+
|   59305d2f1e6c3a707c805792 | core.local      | admin        | succeeded (0s elapsed)  | Thu, 01 Jun     | Thu, 01 Jun   |
|                            |                 |              |                         | 2017 18:30:07   | 2017 18:30:07 |
|                            |                 |              |                         | UTC             | UTC           |
|   59305d321e6c3a707c805795 | core.remote     | admin        | succeeded (2s elapsed)  | Thu, 01 Jun     | Thu, 01 Jun   |
|                            |                 |              |                         | 2017 18:30:10   | 2017 18:30:12 |
|                            |                 |              |                         | UTC             | UTC           |
| + 59305d371e6c3a707c805798 | packs.install   | admin        | succeeded (16s elapsed) | Thu, 01 Jun     | Thu, 01 Jun   |
|                            |                 |              |                         | 2017 18:30:15   | 2017 18:30:31 |
|                            |                 |              |                         | UTC             | UTC           |
| + 593060831e6c3a707c8057b3 | examples        | admin        | failed (21s elapsed)    | Thu, 01 Jun     | Thu, 01 Jun   |
|                            | .mistral-basic  |              |                         | 2017 18:44:19   | 2017 18:44:40 |
|                            |                 |              |                         | UTC             | UTC           |
|   593060ee1e6c3a707c8057b8 | core.local      | admin        | running (10s elapsed)   | Thu, 01 Jun     |               |
|                            |                 |              |                         | 2017 18:46:06   |               |
|                            |                 |              |                         | UTC             |               |
| + 593060f41e6c3a707c8057bb | examples        | admin        | running (4s elapsed)    | Thu, 01 Jun     |               |
|                            | .mistral-basic  |              |                         | 2017 18:46:12   |               |
|                            |                 |              |                         | UTC             |               |
+----------------------------+-----------------+--------------+-------------------------+-----------------+---------------+
vagrant@metropolis:~$ sudo service st2actionrunner stop
st2actionrunner stop/waiting
vagrant@metropolis:~$ st2 execution list
+----------------------------+-----------------+--------------+-------------------------+-----------------+---------------+
| id                         | action.ref      | context.user | status                  | start_timestamp | end_timestamp |
+----------------------------+-----------------+--------------+-------------------------+-----------------+---------------+
|   59305d2f1e6c3a707c805792 | core.local      | admin        | succeeded (0s elapsed)  | Thu, 01 Jun     | Thu, 01 Jun   |
|                            |                 |              |                         | 2017 18:30:07   | 2017 18:30:07 |
|                            |                 |              |                         | UTC             | UTC           |
|   59305d321e6c3a707c805795 | core.remote     | admin        | succeeded (2s elapsed)  | Thu, 01 Jun     | Thu, 01 Jun   |
|                            |                 |              |                         | 2017 18:30:10   | 2017 18:30:12 |
|                            |                 |              |                         | UTC             | UTC           |
| + 59305d371e6c3a707c805798 | packs.install   | admin        | succeeded (16s elapsed) | Thu, 01 Jun     | Thu, 01 Jun   |
|                            |                 |              |                         | 2017 18:30:15   | 2017 18:30:31 |
|                            |                 |              |                         | UTC             | UTC           |
| + 593060831e6c3a707c8057b3 | examples        | admin        | failed (21s elapsed)    | Thu, 01 Jun     | Thu, 01 Jun   |
|                            | .mistral-basic  |              |                         | 2017 18:44:19   | 2017 18:44:40 |
|                            |                 |              |                         | UTC             | UTC           |
|   593060ee1e6c3a707c8057b8 | core.local      | admin        | abandoned               | Thu, 01 Jun     |               |
|                            |                 |              |                         | 2017 18:46:06   |               |
|                            |                 |              |                         | UTC             |               |
| + 593060f41e6c3a707c8057bb | examples        | admin        | failed (25s elapsed)    | Thu, 01 Jun     | Thu, 01 Jun   |
|                            | .mistral-basic  |              |                         | 2017 18:46:12   | 2017 18:46:37 |
|                            |                 |              |                         | UTC             | UTC           |
+----------------------------+-----------------+--------------+-------------------------+-----------------+---------------+
vagrant@metropolis:~$ sudo dpkg -l | grep st2
ii  st2                                      2.3dev-93                                  amd64        StackStorm Event-driven automation
ii  st2chatops                               2.3dev-3                                   amd64        St2Chatops - StackStorm ChatOps.
ii  st2mistral                               2.3dev-99                                  amd64        st2 Mistral workflow service.
ii  st2web                                   2.3dev-2                                   amd64        St2Web - StackStorm Web UI
```

**Comment by lakshmi-kannan** [comment] 2017-06-02 00:44
https://gist.github.com/lakshmi-kannan/d749d96e72a70bee45ce6ea6800693c4. The core.local action task shows status as failed and parent workflow also shows as failed. I was expecting core.local to be abandoned but it seems like the task status is failed. 

Here is logs for a standalone core.local task
```
ubuntu@st2test:~$ st2 run core.local cmd="sleep 50; echo covfefe" -a
To get the results, execute:
 st2 execution get 5930b4a555fc8c2ffef4ecb0
ubuntu@st2test:~$ st2 execution get 5930b4a555fc8c2ffef4ecb0
id: 5930b4a555fc8c2ffef4ecb0
status: running (5s elapsed)
parameters:
  cmd: sleep 50; echo covfefe
result: None
ubuntu@st2test:~$ sudo service st2actionrunner stop
ubuntu@st2test:~$ st2 execution get 5930b4a555fc8c2ffef4ecb0
id: 5930b4a555fc8c2ffef4ecb0
status: failed (13s elapsed)
parameters:
  cmd: sleep 50; echo covfefe
result:
  failed: true
  return_code: -15
  stderr: ''
  stdout: ''
  succeeded: false
ubuntu@st2test:~$
```

**Comment by bigmstone** [comment] 2017-06-02 19:51
Can't reproduce. Closing.

**Closed by bigmstone** 2017-06-02 19:51 UTC
Labels: bug
