### ISSUE TITLE
404 error when disabling a sensor

### ISSUE THREAD

**Issue by cbrenton** [StackStorm/st2#2918] opened 2016-09-21 20:53 UTC
I am unable to disable any sensors via the command line, and I get this error every time I try:
`$ st2 sensor disable ubuild.UBuildActivitySensor`
`ERROR: 404 Client Error: Not Found`
`MESSAGE: argument of type 'SensorTypeAPI' is not iterable for url: http://127.0.0.1:9101/v1/sensortypes/57b78f40e1382366f4445113`

**Comment by Kami** [comment] 2016-09-22 05:51
@cbrenton Which version are you using?

This was fixed in the latest v2.0.0 release.

This also seems like a duplicate of #2878.

**Comment by cbrenton** [comment] 2016-09-22 17:52
1.6. I guess it's time to upgrade 😿

**Comment by Kami** [comment] 2016-09-23 07:24
Yeah, do upgrade, v2.0 includes other fixes and improvements :)

**Comment by Kami** [comment] 2016-09-23 07:24
I'll go ahead and close this ticket now. If after upgrade to v2.0.0, this issue still exists, please feel free to re-open it.

**Closed by Kami** 2016-09-23 07:24 UTC
