### ISSUE TITLE
complex trigger payload fails silently

### ISSUE THREAD

**Issue by bri365** [StackStorm/st2#2926] opened 2016-09-27 20:22 UTC
A trigger (vsphere.event) with complex payload including an array of objects (list of dictionaries in python) has been working up to st2 v1.6.0.  In v2.0.0 the same triggers fail to show up in 'st2 trigger-instance list' although they do show up in st2sensorcontainer.log as "Dispatching trigger..." with the list of dicts. No errors are reported in any log files.  Replacing the array of objects with an array of strings results in the trigger making it all the way though the system, as does an empty array.  In the examples below, the first one works, the second one fails:

```
vsphere_event_sensor.log:2016-09-27 18:22:17,079 [st2.SensorWrapper.vsphere.VSphereEventSensor|8356|MainThread] | reactor.py:dispatch:106 (DEBUG) - Dispatching trigger (trigger=vsphere.event,payload={'trace_context': None, 'trigger': 'vsphere.event', 'payload': {'moref': u'vm-81', 'change_set': ['change_set', 'ch ch changes'], 'action': 'VmReconfigured', 'timestamp': '2016-09-27 18:22:14.522999+0000', 'vsphere_host': u'192.168.148.100', 'previous_references': ['referring_objects', 'more objects'], 'type': 'VmEvent', 'vsphere_uuid': '6697df20-ffff-cccc-aaaa-6e16f518bdf9'}})
vsphere_event_sensor.log:2016-09-27 18:28:43,039 


[st2.SensorWrapper.vsphere.VSphereEventSensor|8678|MainThread] | reactor.py:dispatch:106 (DEBUG) - Dispatching trigger (trigger=vsphere.event,payload={'trace_context': None, 'trigger': 'vsphere.event', 'payload': {'moref': u'vm-81', 'change_set': ['change_set', 'ch ch changes'], 'action': 'VmReconfigured', 'timestamp': '2016-09-27 18:28:41.280999+0000', 'vsphere_host': u'192.168.148.100', 'previous_references': [{'moref': 'vm-81-vnic-Network adapter 1', 'object_type': 'VNIC'}], 'type': 'VmEvent', 'vsphere_uuid': '6697df20-ffff-cccc-aaaa-6e16f518bdf9'}})
```

Resulting 'st2 trigger-instance list' output (the second trigger instance never makes it through):

```
| 57eab8c8e15cdb0a6a477ba2 | core.st2.key_value_pair.update | Tue, 27 Sep 2016 18:22:00 UTC | processed |
| 57eab8c9e15cdb0a6a477ba8 | core.st2.generic.actiontrigger | Tue, 27 Sep 2016 18:22:01 UTC | processed |
| 57eab8c9e15cdb0a6a477ba9 | core.st2.generic.actiontrigger | Tue, 27 Sep 2016 18:22:01 UTC | processed |
| 57eab8d9e15cdb0a6a477baa | vsphere.event                  | Tue, 27 Sep 2016 18:22:17 UTC | processed |
| 57eab8dbe15cdb0a6a477bb2 | core.st2.generic.actiontrigger | Tue, 27 Sep 2016 18:22:19 UTC | processed |
| 57eab8dbe15cdb0a6a477bb3 | core.st2.generic.actiontrigger | Tue, 27 Sep 2016 18:22:19 UTC | processed |
| 57eab8dce15cdb0a6a477bb4 | core.st2.generic.actiontrigger | Tue, 27 Sep 2016 18:22:20 UTC | processed |
| 57eab8dde15cdb0a6a477bb5 | core.st2.generic.actiontrigger | Tue, 27 Sep 2016 18:22:21 UTC | processed |
| 57eab8dee15cdb0a6a477bb6 | core.st2.generic.actiontrigger | Tue, 27 Sep 2016 18:22:22 UTC | processed |
| 57eaba4ae15cdb0a6a477bb7 | core.st2.sensor.process_spawn  | Tue, 27 Sep 2016 18:28:26 UTC | processed |
| 57eaba4ae15cdb0a6a477bb9 | core.st2.sensor.process_spawn  | Tue, 27 Sep 2016 18:28:26 UTC | processed |
| 57eaba4be15cdb0a6a477bbb | core.st2.sensor.process_spawn  | Tue, 27 Sep 2016 18:28:27 UTC | processed |
| 57eaba4de15cdb0a6a477bbd | core.st2.sensor.process_exit   | Tue, 27 Sep 2016 18:28:29 UTC | processed |
| 57eaba4ee15cdb0a6a477bbf | vsphere.vsphere_cached | Tue, 27 Sep 2016 18:28:30 UTC | processed |
| 57eaba4ee15cdb0a6a477bc1 | core.st2.key_value_pair.update | Tue, 27 Sep 2016 18:28:30 UTC | processed |
| 57eaba50e15cdb0a6a477bc9 | core.st2.generic.actiontrigger | Tue, 27 Sep 2016 18:28:32 UTC | processed |
| 57eaba50e15cdb0a6a477bca | core.st2.generic.actiontrigger | Tue, 27 Sep 2016 18:28:32 UTC | processed |
| 57eac860e15cdb0a6a477bcb | vsphere.vsphere_cached | Tue, 27 Sep 2016 19:28:32 UTC | processed |
```

**Comment by bri365** [comment] 2016-09-27 20:42
We traced it down through st2common/transport/publishers.py and the payload is ok at that point.  Perhaps pickle is losing it in kombu?

**Comment by bri365** [comment] 2016-09-27 21:14
Checking to see if this is a python version related issue...

**Comment by bri365** [comment] 2016-09-28 16:16
Nope; happening with Python 2.7.5 and 2.7.11 on v2.0.0.

**Comment by bri365** [comment] 2016-09-28 18:21
Looks like it may be a missing library for fancy serialization/deserialization that we forgot to include.  An error showed up in st2rulesengine.log: 
ERROR mixins [-] Can't decode message body: DecodeError(ImportError('No module...
Wouldn't have thought to check there...
Which piece of code would/should have tried to decode the message to put the trigger instance into mongo?  Should it have reported an error as well?

**Comment by Kami** [comment] 2016-09-29 15:24
Thanks for the report.

From top of my head, there are no changes we made in v2.0.0 which could affect that. Having said that -

Right now we use pickle to serialize and de-serialize messages which are send via the message bus. Pickle should come with a standard Python distribution so not sure how it could be missing. It could be trying to use cPickle which might not be available, but if it's not available, it usually just falls back into pickle library written in pure Python.

Can you please gist the whole "Can't decode message body" error message and I will look into it.

**Comment by Kami** [comment] 2016-09-29 15:25
Another question - did you happen to update vsphere library or similar?

**Comment by Kami** [comment] 2016-09-29 15:38
To sum it up - the issue is related to a dictionary containing a type which can't be serialized.

All the types inside the trigger payload must be simple types (lists, dicts, integers, booleans) which can be serialized (custom defined class instances and similar are not supported).

The problem apparently is that error message is not that straight-forward and user-friendly. I did make a related change in the distant past (throw a more user-friendly exception inside sensor contain on unserilizable type), but there might be some other places which don't throw a user friendly exception yet - I will look into it.

**Comment by Kami** [comment] 2016-09-29 15:43
After some more thought I remember why I didn't fix / improve this in the past.

Checking the whole payload recursively that it only contains simple types would be too expensive (we would need to perform that check on every dispatch call) so I decided not to do it.

In the future we plan to move away from pickle to json for serialization and that should solve this problem - #/1761.

**Comment by Kami** [comment] 2016-09-29 15:49
I will close this, let's please continue in #1761 (feel free to upvote that issue there so we can prioritize it accordingly :)).

**Closed by Kami** 2016-09-29 15:49 UTC
