### ISSUE TITLE
RBAC Authorisation for action execution fails if CLI/UI permissions are missing

### ISSUE THREAD

**Issue by aniruddhamonker** [StackStorm/st2#3156] opened 2017-01-11 21:23 UTC
```sh
bwc:/opt/stackstorm/rbac/roles# cat executeCore.yaml

---
    name: "executeCore"
    description: "Allow execution of Core pack actions"
    enabled: true
    permission_grants:
        -
            resource_uid: "action:core:local"
            permission_types:
               - "action_execute"

bwc:~# st2 run core.local cmd=date
ERROR: 403 Client Error: Forbidden
MESSAGE: User "st2admin" doesn't have required permission "runner_type_list" for url: http://127.0.0.1:9101/v1/runnertypes/?name=local-shell-cmd
```

**Comment by LindsayHill** [comment] 2017-06-19 18:08
Probably worth verifying that this behavior is unchanged with 2.3, since we've got lots of RBAC-related changes there?

I guess we also need to review: Is this how we want it to work? Maybe we do? The CLI client does things like checking runner types, before executing. Presumably if you just made a call to the executions API, it would execute the action with those permissions?

**Comment by LindsayHill** [comment] 2018-03-20 00:08
Closing: this is expected behavior. User has access to execute action via API.

**Closed by LindsayHill** 2018-03-20 00:08 UTC
Labels: status:to be verified, status:under discussion
