### ISSUE TITLE
Feature request: conditional parameters input

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#2221] opened 2015-11-18 16:14 UTC
We definitely need to allow passing specific parameters on a conditional basis in the workflows, something like this:

```
action: act.ref
input:
  param1: <% $.param1 %>
     when: <% $.param1 != '' %>
```

This is to let passing parameters to actions, where such parameters are optional. A live example for better understanding: let's say I have a mistral workflow for booting up a VM. The user, who fires up this workflow may supply or not supply a name for `availability-zone`, which is the optional parameter for `openstack.server.create` action. Without conditional parameter pass user must know which zone to boot it in, even if he wants to rely on automatic choice by Openstack. The `server.create` action requires a string, and doesn't allow 'None'. Would be nice to let us decide when to pass a parameter in the workflow rather than changing wrappers for CLI commands.

**Comment by armab** [comment] 2020-09-15 11:15
Closing as the issue is mistral related, which is deprecated now.

@emptywee Feel free to ropen a new issue for Orquesta if you see a fit.

**Closed by armab** 2020-09-15 11:15 UTC
Labels: feature
