### ISSUE TITLE
Trigger dispatched from sensor not reaching rulesengine

### ISSUE THREAD

**Issue by andrew-regan** [StackStorm/st2#3393] opened 2017-05-05 12:28 UTC
**Release:** StackStorm 2.2.1
**Issue:** A trigger that is dispatched in the first polling cycle of a polling sensor intermittently is never processed by the st2rulesengine. 
**Gist:** https://gist.github.com/andrew-regan/dbaf5d2d18731ab316887ad2a0650071

**Comment by andrew-regan** [comment] 2017-05-05 12:28
Let me know if you want me to attach the full logs from the Gist above?

**Comment by LindsayHill** [comment] 2017-06-19 17:08
I think this is right, but just to check: Any future triggers that get dispatched will be processed by st2rulesengine? It's just an issue related to a trigger that gets dispatched with the first polling cycle?

**Comment by andrew-regan** [comment] 2017-06-21 18:43
We've only seen this once in the first polling cycle..

**Comment by LindsayHill** [comment] 2017-06-21 20:16
Odd. Must be a timing thing, related to initialization.

**Comment by LindsayHill** [comment] 2017-08-04 17:18
I believe this PR may be the fix: https://github.com/StackStorm/st2/pull/3648

Good news: if it is - and it seems likely - it will be fixed in 2.4

**Comment by andrew-regan** [comment] 2017-08-04 17:19
Thanks for the update!

**Comment by LindsayHill** [comment] 2017-08-04 17:20
If you get a chance, you might want to test it out with new dev packages as they get built (should be published now, or shortly)

**Comment by LindsayHill** [comment] 2018-06-19 14:10
Should have been fixed with #3648, shipped in 2.4.

**Closed by LindsayHill** 2018-06-19 14:10 UTC
Labels: status:to be verified

**Comment by Sphinxs** [comment] 2019-12-18 19:35
In the Python client I'm dispatching two triggers, but only one is executed, any tips?

The dispatch:

```python
self._sensor_service.dispatch(
        trigger="pack.trigger",
        payload=payload,
        trace_tag=trace_tag_request
)
```

**Comment by Kami** [comment] 2019-12-18 19:41
It would be good to see ``st2sensorcontainer`` service log with DEBUG log level, otherwise it's really impossible to say what is going on.

And if the the trigger makes it out of the sensor container service, then we would also need to see st2rulesengine service DEBUG log level logs.

https://docs.stackstorm.com/troubleshooting/debug_mode.html

**Comment by Sphinxs** [comment] 2019-12-18 20:10
@Kami , thanks. I was using the sensor troubleshooting, but using the `st2sensorcontainer` log I have found where was the problem.

**Comment by Kami** [comment] 2019-12-18 20:11
Great to hear that you figured it out.

Would you mind sharing the root cause (it may help other users). Did it have something to do with the failed trigger payload schema validation? Or payload containing non-native / simple Python types?

**Comment by Sphinxs** [comment] 2019-12-18 20:30
There was three problems:

1. The payload was valid, but the usage not  `"echo 'Some text {{ trigger.payload }}'"`
, according the log
2. The Docker Compose is not running the `command: ["st2 pack install file://opt/stackstorm/packs/stackstorm/pack_name"]` to register my pack

3. According to the sensor troubleshuting `/opt/stackstorm/st2/bin/st2sensorcontainer --config-file=/etc/st2/st2.conf --debug` there is an address that is address already in use, but this doesn't cause any error... I have only one port that I have specified (6000)  and the other ones are from the Stack Storm, using `netstat -nlp` and searching in the configurations I have not found a port that is in use and that set in another place
