### ISSUE TITLE
Validation error when passing an optional integer parameter to child action from action-chain

### ISSUE THREAD

**Issue by rakeshrm** [StackStorm/st2#4099] opened 2018-05-01 17:20 UTC
## Summary:
In an action-chain if an optional integer parameter is passed to a child action and the parameter is not supplied while executing the action-chain, it fails with a validation error:

```
Failed to cast value "None" (type: unicode) for parameter "frequency" of type "integer": invalid literal for int() with base 10: 'None'.
```

## Details
I have the following `remote-shell-cmd` action

`test_update_remote.yaml`

```yaml
---
    name: 'test_update_remote'
    runner_type: 'remote-shell-cmd'
    description: >
        Remote shell command runner to update
    enabled: true
    entry_point: ''
    parameters:
        frequency:
            type: 'integer'
            description: 'Set the update frequency for the source. 0 means no automatic update'
            required: false
        category:
            type: 'string'
            description: 'Set the source category'
            required: false
        cmd:
            immutable: true
            default: 'update {{args}}'
        args:
            description: 'Command line arguments passed to the script'
            default: '{% if frequency %} --frequency {{frequency}}{% endif %} {% if category %} --category {{category}}{% endif %}'
        hosts:
            required: true
            type: string
            description: "The addresses of the host"
            default: "{{ config_context.default_host }}"
        username:
            required: true
            type: string
            description: "The username for logging into the host"
            default: "{{ config_context.default_user }}"
```

This action is called from within an action chain as defined below:
`test_update.yaml`

```yaml
---
    name: 'test_update'
    runner_type: 'action-chain'
    description: 'Update Frequency'
    enabled: true
    entry_point: chains/test_update.yaml
    parameters:
        frequency:
            type: 'integer'
            description: 'update frequency'
            required: false
        category:
            type: 'string'
            description: 'update category'
            required: false
```

`chains/test_update.yaml`

```yaml
---
chain:
-
    name: run_command
    ref: mypack.test_update_remote
    parameters:
        frequency: '{{ frequency }}'
        category: '{{ category }}'

default: run_command
```

Notice that the parameter `frequency` is an optional parameter of type `integer` (`required: false`).
The action-chain `test_update` is simply taking all the parameters and passing it to the action `test_update_remote` as it is.

When the `test_update` action is run it fails with the following error:
```
stackstorm-virtualbox$ st2 run -t $TOKEN mypack.test_update category=test
.
id: 5ae89ddd25acbf61121dadba
action.ref: mypack.test_update
parameters: 
  category: test
status: failed
error: Failed to cast value "None" (type: unicode) for parameter "frequency" of type "integer": invalid literal for int() with base 10: 'None'. Perhaps the value is of an invalid type?
traceback:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/container/base.py", line 119, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/opt/stackstorm/runners/action_chain_runner/action_chain_runner/action_chain_runner.py", line 295, in run
    return self._run_chain(action_parameters)
  File "/opt/stackstorm/runners/action_chain_runner/action_chain_runner/action_chain_runner.py", line 486, in _run_chain
    action_params=action_parameters, context_result=context_result)
  File "/opt/stackstorm/runners/action_chain_runner/action_chain_runner/action_chain_runner.py", line 720, in _get_next_action
    parent_context=parent_context)
  File "/opt/stackstorm/runners/action_chain_runner/action_chain_runner/action_chain_runner.py", line 779, in _build_liveaction_object
    params=resolved_params)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/models/utils/action_param_utils.py", line 128, in cast_params
    raise ValueError(msg)

start_timestamp: Tue, 01 May 2018 17:03:25 UTC
end_timestamp: Tue, 01 May 2018 17:03:25 UTC
result: See error and traceback.
```

## Observations
It appears that when the optional parameter is not supplied to the `test_update` action, it passes `None` as expected. However, when the action-chain receives the `None` values, it evaluates the expression ` frequency: '{{ frequency }}'` as string `"None"`, which is passed to the `test_update_remote` action. There it fails the validation since it got a string while it expected an integer.

**NOTE**: 
1) This works fine if the action-chain is replaced with a mistral-v2 workflow
2) The behaviour is same regardless of the child action type. I tried the same with a python action taking an interger parameter.

## Workaround
Using mistral-v2 workflow instead of action-chain seems to work fine

P.S. If you are using the above example to reproduce the issue, don't forget to change the `config_context.*` values in `test_update_remote.yaml` to your actual values.

**Comment by nmaludy** [comment] 2018-05-01 17:33
Duplicate of https://github.com/StackStorm/st2/issues/4096

**Comment by LindsayHill** [comment] 2018-09-12 21:41
Will just track this in #4096

**Closed by LindsayHill** 2018-09-12 21:41 UTC
