### ISSUE TITLE
Carry more data in core.st2.generic.inquiry while consuming inquiry in Rule

### ISSUE THREAD

**Issue by wyjuly** [StackStorm/st2#3995] opened 2018-02-09 05:34 UTC
Hi there,

Is that possible that inquiry trigger can carry more data besides the trigger ID(execution ID)?

From the example in [https://docs.stackstorm.com/inquiries.html](url), 
```
---
name: "notify_inquiry"
pack: "examples"
description: Notify relevant users of an Inquiry action
enabled: false

trigger:
  type: core.st2.generic.inquiry

action:
  ref: slack.post_message
  parameters:
    channel: "#{{ trigger.route }}"
    message: 'Inquiry {{trigger.id}} is awaiting an approval action'
```

The rule can only get trigger's ID while it's fired. Suppose we want to provision vms, and create inquiry if the provisioning failed, also consume the trigger in a rule and send mail for this. Now we find that we can only send the trigger's ID, the schema of the trigger cannot be retrieved.
Finally we'll find a lot of mails with only inquiry ID, and execute 
`st2 inquiry list `
will get a lot of items. But we don't know the detailed of these inquiries such as VM name, VM IP etc. 

Is that possible that more properties or parameters could be placed into the inquiry trigger, so they can be passed to rule? Thanks.

**Comment by armab** [comment] 2018-02-09 12:45
Perfectly valid example.
This also sounds like a duplicate of [Add additional context to Inquiries #3952](https://github.com/StackStorm/st2/issues/3952).

If it ^^ describes your use case, let's please include all the details in the above issue.

**Comment by wyjuly** [comment] 2018-02-09 13:40
@armab Yes that's exactly what I put here. Thanks. Will tracking #3952.

**Comment by armab** [comment] 2018-02-09 17:21
I'm closing this in favor of #3952 then.

Please submit in that issue your use case, - more user requests will help to prioritize it.

Thank you!

**Closed by armab** 2018-02-09 17:21 UTC
Labels: duplicate
