### ISSUE TITLE
Mistral API slowdown and timeouts in st2 v2.2.0 and beyond

### ISSUE THREAD

**Issue by tim-ireland** [StackStorm/st2#3439] opened 2017-05-30 17:58 UTC
### Environment:
```
mistral 2.2.1
st2 2.2.1
```

I have a sensor which dispatches triggers for various events.  Those triggers then match rules which call mistral workflows to process each event.

The python code in the individual actions that are called in the workflow run on the order of 3-4 ms.  The REST calls against the mistral API seem to slow down significantly.  In local experiments it's takes on the order of 250 events over a 5 minute period to trigger this condition.

### Problem signature

```python
2017-05-24 14:14:10,697 139630695351792 INFO wsgi [-] 127.0.0.1 "POST /v2/executions HTTP/1.1" status: 500  len: 307 time: 60.0516961
2017-05-24 14:14:11,063 139630698172240 ERROR api [-] Server-side error: "MessagingTimeout: Timed out waiting for a reply to message ID 7600356079a3431aab48582aa71cdea3". Detail:
Traceback (most recent call last):
  File "/opt/mistral/virtualenv/lib/python2.7/site-packages/wsmeext/pecan.py", line 85, in callfunction
    result = f(self, *args, **kwargs)
  File "/opt/mistral/virtualenv/lib/python2.7/site-packages/mistral/api/controllers/v2/execution.py", line 210, in post
    **exec_dict.get('params') or {}
  File "/opt/mistral/virtualenv/lib/python2.7/site-packages/mistral/engine/rpc_backend/rpc.py", line 148, in decorator
    _wrap_exception_and_reraise(e)
  File "/opt/mistral/virtualenv/lib/python2.7/site-packages/mistral/engine/rpc_backend/rpc.py", line 123, in _wrap_exception_and_reraise
    raise exc.MistralException(message)
MistralException: MessagingTimeout: Timed out waiting for a reply to message ID 7600356079a3431aab48582aa71cdea3
```

### Symptoms

As I run a test that sends new events (at a rate of a 3-4 events per second over 5 minutes) I can watch the API response times gradually slow in the mistral.log file.  Once the 60 sec threshold is hit, future workflow executions seem to be thrown on the floor.   

### Theory

I have a related question about the mistral backend:  https://github.com/StackStorm/st2/issues/3429.  The current st2 mistral branch appears to have this blocking behavior:
https://github.com/StackStorm/mistral/blame/master/mistral/engine/rpc_backend/oslo/oslo_server.py

It seems that this behavior was introduced between st2 v2.1.1 (seems to scale just fine - currently re-testing with this older branch) and st2 v2.2.0.  

From the trace above, the mistral `post()` call in `api/controllers/v2/execution.py` uses the `rpc.get_engine_client` to get an instance of the client to call the backend.  Then calls `engine.start_workflow`:

```python
result = engine.start_workflow(
            exec_dict.get('workflow_id', exec_dict.get('workflow_name')),
            exec_dict.get('input'),
            exec_dict.get('description', ''),
            **exec_dict.get('params') or {}
        )
```
The start_workflow call invokes a synchronous api call ```"""Synchronous call of RPC method. Blocks the thread and wait for method result."""```

```python
return self._client.sync_call(
            auth_ctx.ctx(),
            'start_workflow',
            workflow_identifier=wf_identifier,
            workflow_input=wf_input or {},
            description=description,
            params=params
        )
``` 
So now we have a blocking call on the rpc client, and a blocking behavior at the rpc server when enqueuing new workflow `executions` and `action_executions`.

**Comment by andrew-regan** [comment] 2017-05-31 12:36
Some more data:
* we rolled back to StackStorm/Mistral v2.1.1 and do not see this issue with the same event load
* we cherry picked the following PR's on top of v2.2.1 and the issue still reproduces: #3412, #3413, and #3420

**Comment by m4dcoder** [comment] 2017-06-01 23:58
I try to reproduce this issue on our upcoming v2.3, installed on a single VM. I'm running ```for i in `seq 500`; do st2 run examples.mistral-basic timeout=600 cmd="sleep 60; date" -a; done```. This basically schedules 500 workflow execution. Each workflow will sleep for a minute. All action executions completed fine. They do take some time to complete as it's limited by the number of action runners. I'm not seeing any MessagingTimeout in the logs.

What is your StackStorm installation like?  Single node?  Multiple nodes?

**Comment by andrew-regan** [comment] 2017-06-02 00:03
Single node.

**Comment by m4dcoder** [comment] 2017-06-02 00:04
Can you try the for loop I used to test?  Can you show us a sample workflow of yours?

**Comment by andrew-regan** [comment] 2017-06-02 00:13
https://gist.github.com/andrew-regan/823a813a85febf05e6c7f9043b65ee7f

**Comment by m4dcoder** [comment] 2017-06-02 23:02
I retest w/ the following workflow, which is a mock up of your example. Still, I'm not able to reproduce any MessagingTimeout error.

```version: "2.0"

sandbox.complex:
    tasks:
        init:
            action: std.noop
            on-success:
                - task1
                - task3

        task1:
            action: core.local
            input:
                cmd: sleep 45
            on-success:
                - task2
        task2:
            action: core.local
            input:
                cmd: sleep 45


        task3:
            action: core.local
            input:
                cmd: sleep 45
            on-success:
                - task4
        task4:
            action: core.local
            input:
                cmd: sleep 45
            on-success:
                - task5
        task5:
            action: core.local
            input:
                cmd: sleep 45```

**Comment by m4dcoder** [comment] 2017-06-05 18:02
Additional info on related issue at https://github.com/StackStorm/st2/issues/3429

**Comment by tim-ireland** [comment] 2017-06-08 14:07
Ok, quick update.  We were running mistral as a monolithic process (launch args 'all').  Breaking mistral out into an api service under gunicorn, and a separate server service (running engine and executor) seems to have improved performance.

However, given the new info in #3429, I'm interested in possibly breaking out the engine_server and executor_server into separate services and running multiple instances of engine_server.

**Comment by m4dcoder** [comment] 2017-06-08 19:08
Yeah, the built in WSGI server in mistral is not scalable. That's why I asked how you installed StackStorm and Mistral at https://github.com/StackStorm/st2/issues/3439#issuecomment-305652320. We typically break out Mistral API and run it with gunicorn. Most of the work is done by StackStorm action runners. Mistral engine/executor is mostly coordinating the workflows. You can scale out Mistral API, engine, and executor servers depending on your workload. I don't think you need to separate the engine/executor though.

**Comment by andrew-regan** [comment] 2017-06-08 19:23
Sorry....I missed this earlier: _Using our install script? Installing individual components manually on your own?_  🤦‍♂️

**Comment by m4dcoder** [comment] 2017-06-08 19:37
@andrew-regan So I'm going to close this issue. If you find other problems, feel free to reach us on Slack or open new issues here.

**Closed** 2017-06-08 19:40 UTC
Labels: bug, regression, status:to be verified
