### ISSUE TITLE
workflow times out in between - Paramiko error: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by riyu94** [StackStorm/st2#4583] opened 2019-03-07 23:13 UTC
Stackstorm workflow exits without completing the workflow in between.

 - Bug Report

st2 2.10.0

While executing one of the core.remote tasks in orquestra workflow, Stackstorm exits without producing any error or output. And found this message in workflow log : Paramiko error: Error reading SSH protocol banner

This is risky, as we had further steps in workflow and stackstorm did not complete it and failed it.

**Comment by LindsayHill** [comment] 2019-03-07 23:15
Can you please post an example workflow to reproduce this? On the face of it, it sounds like your workflow did not have any error handling, so it exited at the failed step (as would be expected)?

**Comment by LindsayHill** [comment] 2019-03-07 23:17
> Stackstorm exits without producing any error or output

And just to clarify, are you saying that the execution exited successfully, or that ST2 processes exited?

What does `st2 execution get <ID>` show for the relevant execution?

**Comment by riyu94** [comment] 2019-03-07 23:18
Sure, I guess I am handling the failed part of the task:
  ldap_check: #ldap check

    action: core.remote

    input:
      
      cmd: 'if [ "$(cat check.err | grep -i sssd | grep NOK)" ] ; then echo "issue flag still active, executing further actions"; exit 1; else echo 'passed'; fi;'

      timeout: 120

      hosts: <% ctx(hosts) %>

      private_key: <% ctx(private_key) %>

    next:

      - when: <% succeeded() %>

        publish:

          - out: "<% ctx(out) %> \n\n- LDAP Check Successful: No Action Taken \nOutput: <% result().get(ctx(hosts)).stdout %>"

        do: lhc_check
        
      - when: <% failed() %>

        publish:

          - out: "<% ctx(out) %> \n\n- LDAP Check Failed \nOutput: <% result().get(ctx(hosts)).stdout %>"

        do: restart_sssd

**Comment by riyu94** [comment] 2019-03-07 23:20
![image](https://user-images.githubusercontent.com/21206708/53996248-8d624d00-40ec-11e9-8f7b-a36a99c03f57.png)
Stackstorm UI

**Comment by LindsayHill** [comment] 2019-03-07 23:26
So the task is marked as failed, which seems correct. The workflow is also marked as failed. What should your workflow have done when the task failed? Without knowing the whole workflow, it's hard to say what it should do.

Try looking at the output of `st2 execution get <ID>` for your workflow. It's possible that you've done something like referenced a non-existent task, or something failed with rendering the `out` variable in your failed step. You should be able to find logs about this if you examine the execution output.

**Comment by riyu94** [comment] 2019-03-07 23:29
Yes, after the task failed, there was another task for it, it did not go there. Instead it just exited.

output of st2 execution get <ID>

  errors:
  - message: Execution failed. See result for details.
    result:
      error: "Unable to connect to any one of the hosts: [u'hostname'].

 connect_errors={
  "hostname": {
    "failed": true,
    "traceback": "Traceback (most recent call last):  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/parallel_ssh.py\", line 261, in _connect    client.connect()  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/paramiko_ssh.py\", line 143, in connect    self.client = self._connect(host=self.hostname, socket=self.bastion_socket)  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/paramiko_ssh.py\", line 705, in _connect    raise SSHException(msg)SSHException: Error connecting to host hostname with connection parameters {'username': 'root', 'key_filename': u'/root/.ssh/id_rsa', 'allow_agent': False, 'hostname': u'hostname', 'look_for_keys': False, 'timeout': 60, 'port': 22}.Paramiko error: Error reading SSH protocol banner.",
    "timeout": false,
    "succeeded": false,
    "stdout": "",
    "stderr": "",
    "error": "Connection error. Error connecting to host hostname with connection parameters {'username': 'root', 'key_filename': u'path', 'allow_agent': False, 'hostname': u'hostname', 'look_for_keys': False, 'timeout': 60, 'port': 22}.Paramiko error: Error reading SSH protocol banner.",
    "return_code": 255
  }
}"
      traceback: "  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py", line 113, in _do_run
    runner.pre_run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/paramiko_ssh_runner.py", line 186, in pre_run
    self._parallel_ssh_client = ParallelSSHClient(**client_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/parallel_ssh.py", line 77, in __init__
    connect_results = self.connect(raise_on_any_error=raise_on_any_error)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/parallel_ssh.py", line 107, in connect
    raise NoHostsConnectedToException(msg)
"
    task_id: ldap_check
    type: error
  - message: 'YaqlEvaluationException: Unable to evaluate expression ''<% result().get(ctx(hosts)).stdout %>''. NoFunctionRegisteredException: Unknown function "#property#stdout"'
    task_id: ldap_check
    task_transition_id: restart_sssd__0
    type: error
  output:
    result: "

Here, I guess the exception seen above needs to be handled and it is not the workflow side.

**Comment by LindsayHill** [comment] 2019-03-07 23:32
Right, that makes sense. It couldn't render `<% result().get(ctx(hosts)).stdout %>`, so the workflow could not continue. You'll have to figure out what error message you want, and how to safely render that.

**Closed by LindsayHill** 2019-03-07 23:32 UTC

**Comment by riyu94** [comment] 2019-03-07 23:33
Ok Thanks @LindsayHill :)

**Comment by LindsayHill** [comment] 2019-03-07 23:35
Good luck figuring it out - post at forum.stackstorm.com or stackstorm-community.slack.com if you're getting stuck.

(Just closing this issue for now since I don't think this is a core code bug)
