### ISSUE TITLE
Trigger payloads containing _ref cause mysterious failures

### ISSUE THREAD

**Issue by mosesschwartz** [StackStorm/st2#2541] opened 2016-02-29 23:36 UTC
I was trying to use Sentry's (https://getsentry.com/welcome/) webhooks to send events to StackStorm and discovered that any trigger payload that includes a key named _ref seems to partially break StackStorm. The trigger instance does get created, but there is an error saying that it was not created (below), and rules for it don't get executed.

To reproduce, create a webhook and run:
$ curl -X POST https://<ST2URL>/api/v1/webhooks/<ST2WEBHOOK>?st2-api-key=<ST2APIKEY> -H "Content-Type: application/json" --data '{"_ref":""}'

```
2016-02-29T23:27:08.665213+00:00 localhost st2rulesengine[894]: INFO 140156253080464 log [-] Matched 0 rule(s) for trigger_instance e6ad1add-83df-4282-95a3-94273fda8962 (type=core.st2.webhook)
2016-02-29T23:27:12.313352+00:00 localhost st2rulesengine[894]: ERROR 140156253080464 log [-] Failed to create trigger_instance {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7f78ab933a50>, 'trigger': {'uid': u'trigger:core:e6ad1add-83df-4282-95a3-94273fda8962:9c072f3ca49748f5a6459bdcb4d898c4', 'parameters': {u'url': u'sentryerrors'}, 'description': None, 'ref_count': 0, 'pack': u'core', 'type': u'core.st2.webhook', 'id': '56d47bd3ef45a605d0d33fdf', 'name': u'e6ad1add-83df-4282-95a3-94273fda8962'}, 'payload': {'body': {'_ref': u''}, 'headers': {'X-Request-Id': 'e7212a0d-67e8-4be4-ab42-319b86b41793', 'X-Forwarded-For': 'IPADDRESS', 'Content-Length': '11', 'Accept': '*/*', 'User-Agent': 'curl/7.43.0', 'Host': 'HOSTNAME', 'X-Real-Ip': 'IPADDRESS', 'Content-Type': 'application/json'}}}.#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/dist-packages/st2reactor/rules/worker.py", line 51, in process#012    raise_on_no_trigger=True)#012  File "/usr/lib/python2.7/dist-packages/st2reactor/container/utils.py", line 60, in create_trigger_instance#012    return TriggerInstance.add_or_update(trigger_instance)#012  File "/usr/lib/python2.7/dist-packages/st2common/persistence/base.py", line 155, in add_or_update#012    model_object = cls._get_impl().add_or_update(model_object)#012  File "/usr/lib/python2.7/dist-packages/st2common/models/db/__init__.py", line 175, in add_or_update#012    return self._undo_dict_field_escape(instance)#012  File "/usr/lib/python2.7/dist-packages/st2common/models/db/__init__.py", line 193, in _undo_dict_field_escape#012    value = getattr(instance, attr)#012  File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/fields.py", line 208, in __get__#012    name=self.name#012  File "/usr/local/lib/python2.7/dist-packages/mongoengine/dereference.py", line 64, in __call__#012    self.reference_map = self._find_references(items)#012  File "/usr/local/lib/python2.7/dist-packages/mongoengine/dereference.py", line 105, in _find_references#012  
```

**Comment by manasdk** [comment] 2016-02-29 23:45
Thanks for the report.

This is a tricky one since the failure comes from a library we use which attributes special meaning to `_ref`. The fix would likely be to ask the library to dereference only up to a specific depth or skip certain properties like payload of a trigger-instance.

**Comment by mosesschwartz** [comment] 2016-02-29 23:48
Thanks for the quick response!

Does the Mongo library parse the payload before it is parsed somewhere in ST2? Seems like you might be able to do some sort of name mangling (and possibly un-mangle on the other side? Though I don't even care about that personally).

**Comment by manasdk** [comment] 2016-02-29 23:54
> Does the Mongo library parse the payload before it is parsed somewhere in ST2?

Yes.

>  Seems like you might be able to do some sort of name mangling

 I thought about name mangle and un-mangle. However, this pretty much means we need to do this recursively for all nested properties of the payload and to also know about all the special properties. Since what we really want is to make webhook payload opaque I feel that skipping the recursive check for payload will be better.

**Comment by enykeev** [comment] 2016-11-21 09:32
Actually, I wasn't able to reproduce this bug anymore.

```
[vagrant@st2packages-el7 ~]$ curl -X POST -H "Content-Type: application/json" --data-binary '{"_ref":"", "name": "st2"}' http://localhost:9101/v1/webhooks/sample?x-auth-token=5f205d8351d24c5181f0ff80e83fd352
{"_ref": "", "name": "st2"}
[vagrant@st2packages-el7 ~]$ st2 execution list -n 1
+--------------------------+------------+--------------+------------------------+------------------------------+-------------------------------+
| id                       | action.ref | context.user | status                 | start_timestamp              | end_timestamp                 |
+--------------------------+------------+--------------+------------------------+------------------------------+-------------------------------+
| 5832be21bf6d843f8d6a049c | core.local | stanley      | succeeded (0s elapsed) | Mon, 21 Nov 2016 09:28:01    | Mon, 21 Nov 2016 09:28:01 UTC |
|                          |            |              |                        | UTC                          |                               |
+--------------------------+------------+--------------+------------------------+------------------------------+-------------------------------+
[vagrant@st2packages-el7 ~]$ st2 execution get 5832be21bf6d843f8d6a049c
id: 5832be21bf6d843f8d6a049c
status: succeeded (0s elapsed)
parameters:
  cmd: 'echo "{''_ref'': u'''', ''name'': ''st2''}" >> ~/st2.webhook_sample.out'
result:
  failed: false
  return_code: 0
  stderr: ''
  stdout: ''
  succeeded: true
[vagrant@st2packages-el7 ~]$ sudo cat /home/stanley/st2.webhook_sample.out
{'_ref': u'', 'name': 'st2'}
```

Going to close it for now. Please reopen if the problem persists.

**Closed by enykeev** 2016-11-21 09:32 UTC
Labels: bug
