### ISSUE TITLE
Mistral Concurrency

### ISSUE THREAD

**Issue by silverbp** [StackStorm/st2#3758] opened 2017-09-21 18:23 UTC
We are having issues with it respecting the concurrency setting in the workflow, It doesn't matter what we put there, it runs everything concurrently whether it's 1, 2, 3, doesn't matter.

It's not respecting it on the deploy_customer task or the download task, but the deploy_customer is a bigger issue for us. In other workflows, it does respect the concurrency setting.

Example workflow below:

```
version: '2.0'

ems.deploy_artifacts:
  description: Deploy Artifacts Workflow.
  type: direct
  input:
    - customers
    - snapshot
    - artifacts
    - environment
    - ignore_deployed
    - dryrun
    - machine
    - source_machine

  output:
    result:
      successful_artifacts: <% $.successful_artifacts %>
      failed_deploys_exist: <% $.failed_deploys_exist %>
      failed_tests_exist: <% $.failed_tests_exist %>
      dryrun: <% $.dryrun %>
      something_deployed: <% $.something_deployed %>

  tasks:
    
    deployment_plan:
      action: ems.deployment_plan  
      input:
        customers: <% $.customers %>
        snapshot: <% $.snapshot %>
        artifacts: <% $.artifacts %>
        source_machine: <% $.source_machine %>
        environment: <% $.environment %>
        ignore_deployed: <% $.ignore_deployed %>
      publish:
        something_deployed: ''
        successful_artifacts: ''
        failed_deploys_exist: ''
        failed_tests_exist: ''
        deployment_plan: <% task(deployment_plan).result.result %>
      on-success:
        - download_artifacts: <% not $.dryrun %>
        - dryrun_deploy_summary: <% $.dryrun and task(deployment_plan).result.result.deployments %>
    
    dryrun_deploy_summary:
      action: ems.deploy_summary
      input:
        environment: <% $.environment %>
        deployments: <% $.deployment_plan.deployments %>
        dryrun: <% $.dryrun %>

    download_artifacts:
      with-items: download in <% $.deployment_plan.downloads %>
      concurrency: 3
      action: ems.download_artifacts
      input:
        artifacts: <% $.download.artifacts %>
        machine: <% $.download.machine %>
      on-success:
        - deploy_customer
    
    deploy_customer:
      join: all
      with-items: deployment in <% $.deployment_plan.deployments %>
      concurrency: 1
      action: ems.deploy_customer
      input:
        customer: <% $.deployment.customer %>
        artifacts: <% $.deployment.artifacts %>
        environment: <% $.environment %>
        machine: <% $.machine %>
      publish:
        deploy_results: <% task(deploy_customer).result.result %>
      on-success:
        - deploy_summary

    deploy_summary:
      join: all
      action: ems.deploy_summary
      input:
        environment: <% $.environment %>
        deployments: <% $.deploy_results %>
        dryrun: <% $.dryrun %>
      publish:
        successful_artifacts: <% task(deploy_summary).result.result.successful_artifacts %>
        failed_deploys_exist: <% task(deploy_summary).result.result.failed_deploys_exist %>
        failed_tests_exist: <% task(deploy_summary).result.result.failed_tests_exist %>
        something_deployed: <% task(deploy_summary).result.result.something_deployed %> 
      on-success:
        - promote_artifacts: <% task(deploy_summary).result.result.successful_artifacts and $.environment = 'int' %>

    promote_artifacts:
      action: ems.promote_artifacts
      input:
        artifacts: <% $.successful_artifacts %>
        environment: int

```

**Comment by m4dcoder** [comment] 2017-09-21 19:11
The issue is caused by `join: all`. When that is specified, the concurrency is not respected. Reported bug upstream to OpenStack at https://bugs.launchpad.net/mistral/+bug/1718754.

**Comment by m4dcoder** [comment] 2017-09-21 19:17
To workaround until bug is fixed, you can define deploy_customer as a separate workflow (and move the with-items definition there) and have deploy_customer task in this workflow call this action.

**Comment by armab** [comment] 2020-09-10 13:28
Closing as part of the Mistral Deprecation game plan in st2 `v3.3.0`.

**Closed by armab** 2020-09-10 13:28 UTC
Labels: bug
