### ISSUE TITLE
`st2 inquiry` is not using `ST2_API_URL` environment variable

### ISSUE THREAD

**Issue by shusugmt** [StackStorm/st2#4186] opened 2018-06-21 01:52 UTC
##### SUMMARY
`st2 inquiry` always tries to connect to 127.0.0.1:9101 regardless of the value set in `ST2_API_URL`

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
`st2 2.7.2, on Python 2.7`

##### OS / ENVIRONMENT / INSTALL METHOD
- `pip install st2client` on CentOS 7

##### STEPS TO REPRODUCE

```
export ST2_API_URL=https://st2.example.com
st2 login hoge
st2 run core.ask
st2 inquiry list
```

##### EXPECTED RESULTS

Connect to the API endpoint specified by `$ST2_API_URL` and retrieves list of inquiries.

##### ACTUAL RESULTS

It tries to connect to 127.0.0.1:9101 and just fails (since our st2 instance is running on remote machine).

```
st2 inquiry list
ERROR: HTTPConnectionPool(host='127.0.0.1', port=9101): Max retries exceeded with url: /exp/inquiries/?limit=50 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x25239d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by armab** [comment] 2018-06-21 11:29
Thanks for reporting this.
Sounds indeed nasty if ST2_API_URL is not taken for inquiries.

**Comment by LindsayHill** [comment] 2018-06-27 23:49
The issue is that Inquiries is still marked as "experimental", so the URL for `st2 inquiries list` looks like `http://127.0.0.1:9101/exp/inquiries/?limit=50`, or for remote requests it would look like `https://my.st2.com/api/exp/inquiries/?limit=50`

In the [st2client code](https://github.com/StackStorm/st2/blob/master/st2client/st2client/client.py#L62), it always maps this to `ST2_BASE_URL:DEFAULT_API_PORT/exp`. Typically this would end up being `http://127.0.0.1:9101/exp`. If the config option `base_url` or environment option ST2_BASE_URL is set, this might end up being `https://my.st2.com:9101/exp`.

This is the code snippet:
```python
self.endpoints['exp'] = '%s:%s/%s' % (self.endpoints['base'], DEFAULT_API_PORT, 'exp')
```

It probably needs similar handling to the api_url:
```python
        if api_url:
            self.endpoints['api'] = api_url
        else:
            self.endpoints['api'] = os.environ.get(
                'ST2_API_URL', '%s:%s/%s' % (self.endpoints['base'], DEFAULT_API_PORT, api_version))
```

We may need to add `exp_url`/ST2_EXP_URL or similar here.

**Comment by shusugmt** [comment] 2018-06-28 02:41
I came up with the pretty much same solution.

```
$ diff client.py client.py.bak
62,63c62
<         self.endpoints['exp'] = os.environ.get(
<             'ST2_API_EXP_URL', '%s:%s/%s' % (self.endpoints['base'], DEFAULT_API_PORT, 'exp'))
---
>         self.endpoints['exp'] = '%s:%s/%s' % (self.endpoints['base'], DEFAULT_API_PORT, 'exp')
```

With `export ST2_API_EXP_URL=https://st2.example.com/exp` the above works fine with our setup. Keep `exp` out from `ST2_API_URL` seems reasonable.

**Comment by LindsayHill** [comment] 2018-06-28 03:04
WIP Code here: https://github.com/StackStorm/st2/tree/issue/exp-url

This adds an ST2_EXP_URL environment option. I've done some basic testing and it works. Not fully tested yet though, and I'm not sure if this is the best approach.

**Comment by LindsayHill** [comment] 2018-06-28 03:09
Will see what others think about my proposal. This might be something we can do in 2.8.1.

**Comment by shusugmt** [comment] 2018-06-28 03:10
@LindsayHill Thanks for the patch! I'll test your code in my environment.

**Comment by LindsayHill** [comment] 2018-06-28 03:29
Thanks, testing would be welcome. Not sure if I've dealt with everything there, but at least it's a viable short-term workaround.

**Comment by shusugmt** [comment] 2018-06-28 03:47
```
git clone https://github.com/StackStorm/st2.git -b issue/exp-url --depth 1
cd st2/st2client
python setup.py install
pip install -U st2client
```

```
st2 --version
st2 2.8dev, on Python 2.7.5
```

```
export ST2_EXP_URL=https://st2.example.com/api/exp
st2 inquiry list
```

Looks good. Thanks!

**Comment by LindsayHill** [comment] 2019-01-15 23:14
Moved inquiries to `/v1` as part of #4495

**Closed by LindsayHill** 2019-01-15 23:14 UTC
Labels: bug, inquiries
