### ISSUE TITLE
[BUG] st2 reload capability leaves stale actions (maybe not only actions)

### ISSUE THREAD

**Issue by dennybaa** [StackStorm/st2#1387] opened 2015-04-27 18:05 UTC
If there was an action and it was removed.
1. `ls -1 /opt/stackstorm/packs/default/actions/*.yaml `
    ```
/opt/stackstorm/packs/default/actions/show.indices.yaml
/opt/stackstorm/packs/default/actions/show.snapshots.yaml
     ```
2. `st2 run packs.load register=all`
3. `st2 action list -p default`

| ref                    | pack    | name           | description    |
|------------------------|---------|----------------|----------------|
| default.show           | default | show           | Show indices   |
| default.show.indices   | default | show.indices   | Show indices   |
| default.show.snapshots | default | show.snapshots | Show snapshots |

We've introduced stale `default.show` action.

**Comment by dennybaa** [comment] 2015-04-27 18:05
`v0.8.3`

**Comment by Kami** [comment] 2015-04-27 18:11
This is the same as #924

Currently it's considered a feature, but we are also discussing how to improve on that and still follow the "infrastructure as code" mantra.

**Comment by jfryman** [comment] 2015-04-27 18:11
Duplicate of https://github.com/StackStorm/st2/issues/924.

Closing, marking original as 'community reported'

**Closed by jfryman** 2015-04-27 18:11 UTC
Labels: bug, duplicate
