### ISSUE TITLE
Allow specifying of a tag to packs.install

### ISSUE THREAD

**Issue by jmound** [StackStorm/st2#2655] opened 2016-04-29 15:36 UTC
From [download.yaml](https://github.com/StackStorm/st2/blob/master/contrib/packs/actions/download.yaml), it appears that you can not specify a git tag to `packs.install`

**Comment by enykeev** [comment] 2016-11-22 06:56
The issue is going to be fixed as a part of 2.1 pack management changes. Stay tuned. Closing.

**Closed by enykeev** 2016-11-22 06:56 UTC
