### ISSUE TITLE
Aliases fail when first letter of format is a capital letter

### ISSUE THREAD

**Issue by ilkirk** [StackStorm/st2#2566] opened 2016-03-09 01:02 UTC
Over the weekend I spent several hours troubleshooting an newly created alias that was based on a template I worked up with @jfryman.  This alias had a format as follows:
  - "Get compliance results for {{ instanceid }}"

When running the action & workflow through the WebUI I could see that everything work as expected. However, when I switched over to my Hubot in HipChat and I issued the command, absolutely nothing happened.  It never triggered the workflow.

In an attempt to further troubleshoot the issue I simplified the format to:
  - "Compliance {{ instanceid }}"

The issue persisted even after I did this.

After taking a couple days off of the effort, I came back to it and removed the capital letter, making the format:
  - "compliance {{ instanceid }}"

Now this worked.

After this worked, I made an attempt with a regular expression which totally prevented the alias from being able to be loaded!  It was:
formats:
  - display: "get compliance results for {{ instanceid }}"
    representation:
    - "(get |show )?[Cc]ompliance\s+(for )?i-([a-zA-Z0-9]+)"

Why in the world does a capital letter that I've very clearly specified in the format should be there?  Further, what is bad with the regular expression situation that makes the alias load blow up?

**Comment by emedvedev** [comment] 2016-03-12 10:36
Hi! Sorry it took me a while to get back to you. I tried a few things to reproduce your issue and see what we can do about it to unblock you.

Firstly, `"Compliance {{ instanceid }}"` not being matched is a bug. I'm looking into it, and you can expect a patch soon.

Secondly, `"(get |show )?[Cc]ompliance\s+(for )?i-([a-zA-Z0-9]+)"` has a few errors:

* the slash in `\s+` should be escaped, otherwise the parser tries to escape `s`: `\\s+` will work;
* the line doesn't have a parameter to match; use `{{ instanceid }}` in place of `i-([a-zA-Z0-9]+)`.

`"(get |show )?[Cc]ompliance\\s+(for )?{{ instanceid }}"` is the line that did it for me.

I'm not closing the issue just yet, because I'm still looking into the uppercase bug.

**Comment by emedvedev** [comment] 2016-03-12 14:47
Will be fixed when https://github.com/StackStorm/hubot-stackstorm/pull/99 is merged. You'll have to update `hubot-stackstorm`.

**Closed** 2016-03-12 16:36 UTC
