### ISSUE TITLE
/usr/bin/st2actionrunner is missing

### ISSUE THREAD

**Issue by psychopenguin** [StackStorm/st2#2397] opened 2016-01-18 17:46 UTC
I was trying to start the st2actionrunner service, but I've discovered the /usr/bin/st2actionrunner file were missing. It was working before, but had been removed from some other process.

As discussed in slack, this seems to happened with other users.

```

psychopenguin [3:37 PM] 
hello guys! i’m having a problem starting the st2actionrunner
```[root@st2centos ~]# st2ctl status
##### st2 components status #####
st2actionrunner is not running.```
i see the init script call `python2.7 /usr/bin/st2actionrunner --config-file /etc/st2/st2.conf` but the file /usr/bin/st2actionrunner doesn’t exist.

[3:37] 
in another machine, the process is running but the file doesn’t exist as well (the process is running since 7th january)

[3:37] 
i’m quite confused on this

[3:38] 
can anyone point me how to debug/fix this?

emptywee [3:39 PM] 
had the same issue. Not exactly sure why it happened, but had to recover a few files from backup image

psychopenguin [3:39 PM] 
that’s weird.```

**Comment by psychopenguin** [comment] 2016-01-18 17:46
Permalink for slack discussion: https://stackstorm-community.slack.com/archives/community/p1453138629012899

**Comment by manasdk** [comment] 2016-01-18 18:11
This has been reported a few times. It is rather mysterious!

**Comment by Kami** [comment] 2016-01-18 18:13
I wonder if there is a race during update-system or something along those lines.

I know we don't run update-system / puppet-apply on cron anymore (at least we shouldn't) so not sure how this could happen.

**Comment by stevemuskiewicz** [comment] 2016-05-13 01:31
Is there a way to view the Slack discussion at all, Slack says "Some older messages won't be shown because your team has over 10,000 messages"

I just hit this issue on a VM that was installed clean from RPM...never had the AIO installer used in it.  This is a little disconcerting that this could happen on a running system!

**Comment by stevemuskiewicz** [comment] 2016-05-13 01:32
>  rpm -V st2
S.5....T.  c /etc/st2/htpasswd
S.5....T.  c /etc/st2/st2.conf
missing     /opt/stackstorm/st2/bin/st2actionrunner
..5....T.    /opt/stackstorm/st2/pip-selfcheck.json
missing     /usr/lib/systemd/system/st2actionrunner.service
missing     /usr/lib/systemd/system/st2actionrunner@.service
missing     /var/run/st2

**Comment by stevemuskiewicz** [comment] 2016-05-13 01:45
And now I'm stuck...

I did a "yum reinstall st2" and that put the files back but st2ctl restart doesn't work and I can't trace what the problem is:

> st2ctl restart --register-all
Failed to stop st2actionrunner.service: Unit st2actionrunner.service not loaded.
Failed to start st2actionrunner.service: Unit st2actionrunner.service failed to load: No such file or directory.
##### st2 components status #####
st2actionrunner is not running.
st2api PID: 3675
st2auth PID: 3681
st2garbagecollector PID: 3687
st2notifier PID: 3693
st2resultstracker PID: 3699
st2rulesengine PID: 3705
st2sensorcontainer PID: 3711
mistral-server PID: 3721
mistral-api PID: 3720
[root@st2 ~]# systemctl start st2actionrunner
Failed to start st2actionrunner.service: Unit st2actionrunner.service failed to load: No such file or directory.
[root@st2 ~]# systemctl -l status st2actionrunner
\u25cf st2actionrunner.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

May 12 21:02:34 st2.plexxi.com systemd[1]: Cannot add dependency job for unit st2actionrunner.service, ignoring: Unit st2actionrunner.service failed to load: No such file or directory.

Where can I go to figure out how to recover this if I can't access the Slack discussion??

**Comment by Kami** [comment] 2016-05-13 07:18
@stevemuskiewicz Which installation method did you use, new packages?

In any case, it looks like installations some how failed half-way through so I would recommend you to try a re-installing using new packages on a fresh server.

**Comment by stevemuskiewicz** [comment] 2016-05-13 13:46
@Kami I used the RPM package install (CentOS 7).  However this wasn't a failure *during* the install, the VM has been running with Stackstorm 1.3 successfully for over a month now.  

I did have to reboot the VM yesterday due to some unrelated network problems, when it came back up was when I noticed that st2actionrunner had the problem.  (However I had successfully rebooted several times over the course of the month and each time ST2 was fine)

Since I needed to get things working, I tried the RPM update to 1.4, it looks like this fixed st2actionrunner but now there is another problem with my chatops throwing exceptions.

If there is something I can check for in any of the logs to try to help with this let me know.

**Comment by manasdk** [comment] 2016-05-13 14:10
@stevemuskiewicz Lets do this over slack?

**Comment by stevemuskiewicz** [comment] 2016-05-13 15:07
@manasdk Sure I'm on Slack now, though I think I may have an idea of what went wrong.  The VM (ESXi) uses a shared/iSCSI datastore that became inaccessible yesterday.  This morning we did a network upgrade which also briefly interrupted the connection and afterward my ssh session to the st2 VM was complaining about "I/O error" for any command I attempted to run.  Also the vmtools were reporting "cannot get disk info" errors on the console.  With the amount of stuff running in st2 all the time, it's conceivable that perhaps st2actionrunner was going during the time of the network interruption enough to corrupt the VM disk.

Still concerning, though I realize it's not your issue nor anything you can really do much about.  (Except maybe to suggest not creating VMs on a shared datastore with less than 100% network reliability!)

**Comment by LindsayHill** [comment] 2016-09-15 15:48
We've tracked this down at last  - it was a bug in the logrotate definition. Fixes have been merged to newer branches, and updated packages will be shipped shortly. You can also manually apply the fix https://github.com/StackStorm/st2/pull/2898

**Closed by LindsayHill** 2016-09-15 15:48 UTC
