### ISSUE TITLE
Documentation correction - TTL Authentication flag

### ISSUE THREAD

**Issue by sootythebear** [StackStorm/st2#1467] opened 2015-05-12 16:06 UTC
Latest 0.9.0 and 0.10dev documentation shows the following:

# with TTL and password
st2 auth yourusername -p yourpassword -t 600

"usage:" however shows the following:

usage: st2 auth [-h] [-j] [-p PASSWORD] [-l TTL] [-t] username

It should also be noted that the TTL value cannot go past the default value (not sure if this is by design), only create tokens that expire with a shortened value to the TTL default.

**Comment by lakshmi-kannan** [comment] 2015-05-12 16:24
@sootythebear Thanks for reporting. It would be cool if you actually opened a PR for the doc fix. The file you'd need to edit is https://github.com/StackStorm/st2/blob/master/docs/source/auth_usage.rst

>It should also be noted that the TTL value cannot go past the default value (not sure if this is by design)

It is by design. We are debating whether to ripple an error to user to say if they specified a TTL that is larger than the maximum configured value in the system. Will keep you posted on that.

**Comment by lakshmi-kannan** [comment] 2015-05-13 15:03
Manually closing. See linked PR.

**Closed by lakshmi-kannan** 2015-05-13 15:03 UTC
