### ISSUE TITLE
Running st2auth in non-gunicorn mode is broken

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#4254] opened 2018-07-19 19:13 UTC
### SUMMARY
During the Docker/K8s work we're trying to run auth, stream, api services in standalone mode that uses eventlet built-in WSGI, without gunicorn overlay. This allows us to avoid using 2 unnecessary logging configs and hardcode some st2.conf settings directly via CLI params.

While other services can run with no problem, `st2auth` fails when client is trying to request st2 token for username:password.

### STEPS TO REPRODUCE
1) Stop st2auth `sudo service stop st2auth`
2) Run st2auth manually in foreground:  `sudo /opt/stackstorm/st2/bin/st2auth --config-file=/etc/st2/st2.conf`
3) Request a token for `st2admin:Ch@ngeMe` pair:
```sh
$ curl -X POST -H 'Authorization: Basic c3QyYWRtaW46Q2hAbmdlTWU=' http://127.0.0.1:9100/tokens
{
    "faultstring": "'{}' is not of type 'object'"
}
```

`st2auth.log`:
```
2018-07-19 18:31:46,668 INFO [-] f590ed84-3e54-4634-89f2-120eb3f956e5 - POST /tokens with query={} (remote_addr='127.0.0.1',method='POST',request_id='f590ed84-3e54-4634-89f2-120eb3f956e5',query={},path='/tokens')
2018-07-19 18:31:46,669 DEBUG [-] Recieved call with WebOb: POST /tokens HTTP/1.0
Accept: */*
Authorization: Basic c3QyYWRtaW46Q2hAbmdlTWU=
Content-Type: text/plain
Host: 127.0.0.1:9100
User-Agent: curl/7.47.0
X-Request-Id: f590ed84-3e54-4634-89f2-120eb3f956e5
2018-07-19 18:31:46,669 DEBUG [-] Match path: /tokens
2018-07-19 18:31:46,670 DEBUG [-] Parsed endpoint: {'x-parameters': [{'in': 'environ', 'type': 'string', 'description': 'source of the request', 'name': 'remote_addr'}, {'in': 'environ', 'type': 'string', 'description': 'set externally to indicate user identity in case of proxy auth', 'name': 'remote_user'}], 'responses': {'201': {'headers': {'x-api-url': {'type': 'string'}}, 'schema': {'$ref': '#/definitions/Token'}, 'examples': {'application/json': {'user': 'st2admin', 'token': '5e86421776f946e98faea36c29e5a7c7', 'expiry': '2016-05-28T12:39:28.650231Z', 'id': '574840001878c10d0b6e8fbf', 'metadata': {}}}, 'description': 'New token has been created'}, 'default': {'description': 'Unexpected error', 'schema': {'$ref': '#/definitions/Error'}}, '401': {'schema': {'$ref': '#/definitions/Error'}, 'examples': {'application/json': {'faultstring': 'Invalid or missing credentials'}}, 'description': 'Invalid or missing credentials has been provided'}}, 'parameters': [{'in': 'header', 'type': 'string', 'description': 'base64 encoded string containing login and password', 'name': 'authorization'}, {'in': 'header', 'type': 'string', 'description': 'set externally to indicate real source of the request', 'name': 'x-forwarded-for'}, {'in': 'body', 'description': 'Lifespan of the token', 'name': 'request', 'schema': {'$ref': '#/definitions/TokenRequest'}}], 'x-log-result': False, 'security': [], 'description': 'Authenticates a user with `Authorization` header and returns a `token`\nobject.\n', 'operationId': 'st2auth.controllers.v1.auth:token_controller.post'}
2018-07-19 18:31:46,670 DEBUG [-] Parsed path_vars: {}
2018-07-19 18:31:46,700 DEBUG [-] API call failed: Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/router.py", line 372, in __call__
    CustomValidator(schema, resolver=self.spec_resolver).validate(data)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
ValidationError: '{}' is not of type 'object'

Failed validating 'type' in schema:
    {'properties': {'ttl': {'minimum': 1, 'type': ['integer', 'null']}},
     'type': 'object'}

On instance:
    '{}'
 (exception_message="'{}' is not of type 'object'",exception_data={'comment': 'Traceback (most recent call last):\n  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/router.py", line 372, in __call__\n    CustomValidator(schema, resolver=self.spec_resolver).validate(data)\n  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate\n    raise error\nValidationError: \'{}\' is not of type \'object\'\n\nFailed validating \'type\' in schema:\n    {\'properties\': {\'ttl\': {\'minimum\': 1, \'type\': [\'integer\', \'null\']}},\n     \'type\': \'object\'}\n\nOn instance:\n    \'{}\'\n', '_headers': None, 'conditional_response': False, 'detail': "'{}' is not of type 'object'", '_app_iter': [''], '_status': '400 Bad Request', '_headerlist': [('Content-Type', 'text/html; charset=UTF-8'), ('Content-Length', '0')]},exception_class='HTTPBadRequest')
2018-07-19 18:31:46,701 DEBUG [-] Match path: /tokens
2018-07-19 18:31:46,701 INFO [-] f590ed84-3e54-4634-89f2-120eb3f956e5 - 400 53 33.332ms (content_length=53,request_id='f590ed84-3e54-4634-89f2-120eb3f956e5',runtime=33.332,remote_addr='127.0.0.1',status=400,method='POST',path='/tokens')

```

**Comment by Kami** [comment] 2018-07-19 21:41
Thanks for reporting this - this is actually not related to gunicorn / standalone mode.

It's a regression introduced a while back and fix has also recently been merged into master. It will work fine if you pass `Content-Type: application/json` with your request. This issue only appears with `Content-Type: text/plain` which is the default.

**Comment by armab** [comment] 2018-07-19 22:14
I just checked with latest st2 `dev` and the error is "a bit" different, so #4225 is somehow related to that:
```
"faultstring": "'' is not of type 'object'"
```
It works OK if I run st2 with gunicorn, but fails in standalone mode.

I can confirm that passing `Content-Type: application/json` leads to a working response.

The problem initially was seen from `st2web`. From what I see It doesn't pass that exact header you want in request, it has however `Accept: application/json, text/plain, */*`.

![st2web-st2auth-bug](https://user-images.githubusercontent.com/1533818/42972979-0ef65e12-8bba-11e8-8280-7387dc50d018.png)

**Comment by Kami** [comment] 2018-07-20 09:22
I just checked again - and yeah, it's an issue related to client provided an invalid / unsupported content type for a particular API endpoint.

/tokens API endpoint takes in an optional body and only valid content-type for that endpoint is `application/json`.

I need to think about how to make this work - either by throwing if unsupported Content-Type is included, or by also handling unsupported content-type, but that has edge cases because we have some other endpoint where `text/plain` content type is valid.

**Closed** 2018-07-20 14:58 UTC
Labels: K8s, bug, service:auth
