### ISSUE TITLE
curl | bash installer doesn't work on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by daniilyar-confyrm** [StackStorm/st2#2818] opened 2016-07-19 21:20 UTC
St2 oneliner installer doesn't configure Mongo properly, so st2 can't connect to Mongo during installation:
```
2016-07-19 21:12:43,990 INFO [-] Connecting to database "st2" @ "0.0.0.0:27017" as user "None".
2016-07-19 21:12:43,991 WARNING [-] Retry on ConnectionError - Cannot connect to database default :
[Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/bin/st2-register-content", line 22, in <module>
    sys.exit(content_loader.main(sys.argv[1:]))
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 347, in main
    setup(argv)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 339, in setup
    common_setup(config=config, setup_db=True, register_mq_exchanges=True)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/script_setup.py", line 86, in setup
    db_setup()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 138, in db_setup
    ssl_match_hostname=cfg.CONF.database.ssl_match_hostname)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/persistence/db_init.py", line 65, in db_setup_with_retry
    ssl_match_hostname=ssl_match_hostname)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/models/db/__init__.py", line 78, in db_setup
    **ssl_kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/mongoengine/connection.py", line 161, in connect
    return get_connection(alias)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/mongoengine/connection.py", line 124, in get_connection
    raise ConnectionError("Cannot connect to database %s :\n%s" % (alias, e))
mongoengine.connection.ConnectionError: Cannot connect to database default :
[Errno 111] Connection refused
```

How to reproduce: 
```
cd /tmp
wget -q https://gist.githubusercontent.com/daniilyar-confyrm/e090a72cc162d46379b7aba8b04eba7f/raw/171882c54382ebed1c0f589338c65f10d0d3deef/Dockerfile -O Dockerfile
sudo docker build -t st2-test .
```

OR spin up a clean AWS EC2 instance with latest Ubuntu 14.04 AMI onboard and execute the following command there:
```
curl -sSL https://stackstorm.com/packages/install.sh | bash -s -- --user=st2admin --password=st2admin
```

**Comment by armab** [comment] 2016-07-20 16:11
I couldn't reproduce it on `AWS EC2`, official `ami-ed82e39e: Ubuntu Server 14.04 LTS (HVM), SSD Volume Type`. Everything worked with the bootstrap script. You can also try [`st2vagrant`](https://github.com/stackstorm/st2vagrant).

Apart of that, provided Docker example can't be used to reproduce the problem. You can't install full `st2` with all services, including `mongo`, `rabbitmq` services in a single `ubuntu:14.04` Docker container, since it ships without any init system, so `service ... start` won't work. 
You can check that `mongodb` service and everything else is not started in such environment.

> If you want dockerized StackStorm, you can monitor this: #2749 and see: https://github.com/stackstorm/st2-dockerfiles, where "the right Docker way" will be used: *1 process/service per container*.

@daniilyar-confyrm Let us know if ^^ that's your issue.

**Comment by armab** [comment] 2016-08-02 13:49
Closing until more info from the reporter.

For now I assume it's related to Docker design ideas, shipping without init system (1 process per container).

**Closed by armab** 2016-08-02 13:49 UTC
Labels: status:need more info

**Comment by daniilyar-confyrm** [comment] 2016-08-03 10:34
After some investigation: 

@armab, you are right about Docker. This was caused by the lack of the init system inside Docker container. So, Mongo just didn't start.

As for st2 installation at clean AWS EC2 instance - I tried running st2 `curl | bash` installation command on t2.medium instance, launched from fresh Ubuntu 14.04 LTS EBS AMI (ami-962fedf6).

This time installation failed with locale errors followed by `psql: could not connect to server: No such file or directory` error. Full installation log is here: http://pastebin.com/HZFnGcXU

**Comment by daniilyar-confyrm** [comment] 2016-08-03 11:21
Let me put some lyric here.

I think, in case of such a modular platform, as StackStorm is, the biggest problem for users is platform installation ;) And, IMO, neither Dockerization, nor massive scripting won't help if the platform itself is too fat.

Look at how ppl install Jenkins. One `apt-get install` command and you are ready to: authenticate, run jobs, use REST API, install plugins and use ui. This `apt-get install` command works well inside Docker container.. Inititally, I wished StackStorm to become such a lightweight platform, so hundreds of tech startups would fall in love with it.. But when I saw st2 PROD requirements (m4.xlarge, >16Gb RAM), my eyes were welling with tears .. Same I can say about platform setup instructions: "install 3 DBs, run DB migrations, install 5 services". Ugh, I am stopping at this point. Please sorry for lyrical digression

**Comment by armab** [comment] 2016-08-03 15:50
@daniilyar-confyrm Yeah. In fact, I have the same feeling.
But you don't know how that installation process looked before without current "bundled" packages :smile: 
There is kind of post-mortem about the topic: https://stackstorm.com/2016/05/03/road-to-packages/

So StackStorm is improving, thanks to feedbacks like this :+1:
