### ISSUE TITLE
Not able to disable a sensor 

### ISSUE THREAD

**Issue by nkelapur** [StackStorm/st2#2878] opened 2016-08-23 22:20 UTC
Getting below error when I am trying to disable the hello-st2 sensor in ST2

vagrant@st2vagrant:/opt/stackstorm/packs$ st2 sensor disable hello-st2.HelloSensor
ERROR: 404 Client Error: Not Found
MESSAGE: argument of type 'SensorTypeAPI' is not iterable for url: http://127.0.0.1:9101/v1/sensortypes/57bcc

vagrant@st2vagrant:/opt/stackstorm/packs$

Sensor code : same as the hello-st2 example
https://github.com/StackStorm/st2/tree/master/contrib/hello-st2

version 
vagrant@st2vagrant:/opt/stackstorm/packs$ st2 --version
st2 1.6.0
vagrant@st2vagrant:/opt/stackstorm/packs$

**Comment by Kami** [comment] 2016-08-24 06:25
Thanks for the report.

Will look into it, never seen an issue like this before.

**Comment by Kami** [comment] 2016-08-24 06:48
It looks like this is an indeed a bug - regression we accidentally introduced in v1.6.0.

I pushed a fix (#2879) and tests so such thing won't happen again in the future. This fix will be included in the next release which should be released in the near future.

Thanks again for the report.

**Comment by Kami** [comment] 2016-09-02 13:41
Fix for that has been included in recently released StackStorm v2.0.0.

Thanks again for reporting this issue.

**Closed by Kami** 2016-09-02 13:41 UTC
