### ISSUE TITLE
st2 api and st2 auth exits with an exception

### ISSUE THREAD

**Issue by johnugeorge** [StackStorm/st2#1841] opened 2015-08-19 07:49 UTC
when st2ctl start is executed, st2api and st2auth starts and then exits with an exception.

```
19 07:46:39,283 140620771120464 INFO log [-] (PID=2303) ST2 Auth API is serving on http://0.0.0.0:9100.
2015-08-19 07:46:39,314 140620771120464 ERROR log [-] (PID=2303) ST2 Auth API quit due to exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2auth/cmd/api.py", line 86, in main
    return _run_server()
  File "/usr/lib/python2.7/dist-packages/st2auth/cmd/api.py", line 75, in _run_server
    wsgi.server(socket, app.setup_app())
  File "/usr/lib/python2.7/dist-packages/st2auth/app.py", line 51, in setup_app
    **app_conf
  File "/usr/local/lib/python2.7/dist-packages/pecan/__init__.py", line 86, in make_app
    app = Pecan(root, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 821, in __init__
    super(Pecan, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 243, in __init__
    root = self.__translate_root__(root)
  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 278, in __translate_root__
    module = __import__(name, fromlist=fromlist)
  File "/usr/lib/python2.7/dist-packages/st2auth/controllers/root.py", line 16, in <module>
    from st2auth.controllers import auth
  File "/usr/lib/python2.7/dist-packages/st2auth/controllers/auth.py", line 34, in <module>
    class TokenController(rest.RestController):
  File "/usr/lib/python2.7/dist-packages/st2auth/controllers/auth.py", line 43, in TokenController
    @jsexpose(body_cls=TokenAPI, status_code=http_client.CREATED)
  File "/usr/lib/python2.7/dist-packages/st2common/models/api/base.py", line 183, in decorate
    pecan_json_decorate(callfunction)
  File "/usr/local/lib/python2.7/dist-packages/pecan/decorators.py", line 89, in decorate
    cfg['argspec'] = getargspec(f)
  File "/usr/local/lib/python2.7/dist-packages/pecan/util.py", line 39, in getargspec
    return getargspec(method)
  File "/usr/local/lib/python2.7/dist-packages/pecan/util.py", line 17, in getargspec
    argspec = inspect.getargspec(method)
  File "/usr/lib/python2.7/inspect.py", line 816, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <class 'st2common.models.api.auth.TokenAPI'> is not a Python function
```

**Comment by dzimine** [comment] 2015-08-19 08:25
Hi John, 

thanks for the report (strange to see it but...) - few questions to help figure it out:

* what version of st2 do you use? `st2auth --version`
* which way did you install it? Running `st2_deploy.sh`? Something else? 
* what is your Linux flavor? 
* what is the version of pecan? Full output of `pip freeze`?

**Comment by Kami** [comment] 2015-08-19 13:47
@johnugeorge I believe a person on IRC encountered the same issue a while ago.

The root cause was the he was using an invalid (latest) version of pecan dependency (he performed a manual installation and didn't use st2_deploy and / or a virtual environment).

You need to use `pecan==0.7.0` as per `requirements.txt`.

If you don't do this already, I would also recommend using clean VM / Cloud Server / Docker containers for deployment so other system dependencies don't interfere with the StackStorm dependencies.

**Comment by johnugeorge** [comment] 2015-08-19 18:27
@Kami  Thanks.  
I was installing stackstorm as given in http://docs.stackstorm.com/install/deb.html
As you said, pecan==0.7.0 was installed as in the requirements file https://downloads.stackstorm.net/releases/st2/0.12.2/requirements.txt
 
I am not planning to  use mistral and by default, mistral is not installed.  But, st2ctl script doesn't start st2web service unless mistral is installed. https://github.com/StackStorm/st2/blob/master/tools/st2ctl#L184 . It fails when mistral service is tried to start and it exits before starting st2web. 

So, I tried to install https://github.com/openstack/mistral which has a different requirements file that has pecan>=0.8.0
This screwed up everything.  What is the right solution? . comment out mistral from st2ctl script?

**Comment by Kami** [comment] 2015-08-19 18:30
@johnugeorge I would recommend re-running st2_deploy.sh on a fresh server / VM (that's the simplest and easiest solution).

By default when using st2_deploy.sh, Mistral requirements are installed into a Mistral-specific virtual environment - this way they don't conflict with StackStorm requirements. In your case though it sounds like you didn't install Mistral in a virtual environment which caused conflicting dependencies issues...

**Comment by Kami** [comment] 2015-08-19 18:31
Also, st2web should indeed be started even if Mistral is not installed. If it's not, it's a bug which we need to fix.

**Comment by Kami** [comment] 2015-08-19 19:17
@johnugeorge Also, as a temporary local workaround for st2ctl issue which happens when Mistral is not installed - you can simply comment out the part which starts mistral in st2ctl inside the `st2start_classic` function.

**Comment by johnugeorge** [comment] 2015-08-19 20:03
@Kami  I have done it as a workaround. Thanks

**Comment by Kami** [comment] 2015-08-19 20:18
No problem.

I will also close this issue and open a new one for st2web start issue.

**Closed by Kami** 2015-08-19 20:18 UTC
