### ISSUE TITLE
title: encrypted data store values are leaked to log file

### ISSUE THREAD

**Issue by mxmader** [StackStorm/st2#4406] opened 2018-10-22 01:07 UTC
##### SUMMARY

if you store an encrypted value in the st2 data store, its value is leaked to the st2 API log when it is retrieved in decrypted form

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
st2 2.9.1, on Python 2.7.15

##### OS / ENVIRONMENT / INSTALL METHOD
Docker - CentOS 7 base image (custom RPM install)

##### STEPS TO REPRODUCE
```
Github keeps giving me HTTP 405, will edit this after creation
```

##### EXPECTED RESULTS
`value` would not be leaked / shown in plain text in log file under `INFO` log level (would be understandable for it to be shown under `DEBUG` log level)

##### ACTUAL RESULTS
see output of reproduction steps

**Comment by Kami** [comment] 2018-10-22 12:45
Closing - duplicate of #4405.

**Closed by Kami** 2018-10-22 12:45 UTC
