### ISSUE TITLE
/api/v1/apikeys not found return 500 instead of 404

### ISSUE THREAD

**Issue by m4dcoder** [StackStorm/st2#3368] opened 2017-04-19 23:06 UTC
`st2 apikey get foobar` return 500. Should it return 404 instead?

**Comment by enykeev** [comment] 2017-04-20 05:09
I'll dig into it, but it would be helpful if you provide a traceback when you encounter similar issue next time.

**Comment by m4dcoder** [comment] 2017-04-20 19:07
Here's the client side error.  ```vagrant@arkham:~/st2$ st2 apikey get foobar
Traceback (most recent call last):
  File "/home/vagrant/projects/stackstorm/st2/st2client/st2client/commands/resource.py", line 162, in get_resource_by_pk
    instance = self.manager.get_by_id(pk, **kwargs)
  File "/home/vagrant/projects/stackstorm/st2/st2client/st2client/models/core.py", line 39, in decorate
    return func(*args, **kwargs)
  File "/home/vagrant/projects/stackstorm/st2/st2client/st2client/models/core.py", line 204, in get_by_id
    self.handle_error(response)
  File "/home/vagrant/projects/stackstorm/st2/st2client/st2client/models/core.py", line 165, in handle_error
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error
Unable to retrieve detailed message from the HTTP response. Expecting value: line 1 column 1 (char 0)
 for url: http://127.0.0.1:9101/v1/apikeys/foobar
API Key "foobar" is not found.```

**Comment by m4dcoder** [comment] 2017-04-20 19:09
and here's what the st2api.log says...

```
2017-04-20 19:06:52,743 140458447461744 INFO logging [-] 6757d1ac-b3fa-417f-9e1f-03d20a0a74d0 - GET /v1/apikeys/fooba with query={} (remote_addr='127.0.0.1',method='GET',request_id='6757d1ac-b3fa-417f-9e1f-03d20a0a74d0',query={},path='/v1/apikeys/foobar')
2017-04-20 19:06:52,749 140458447461744 ERROR auth [-] ('ApiKey matching %s for reference and id not found.', u'fooba')
ApiKeyNotFoundError: ApiKey with key or id=foobar not found.
```

**Comment by humblearner** [comment] 2017-06-14 20:30
Not able to reproduce:

**st2 2.2.1**

```
ubuntu@ansible-st2-ubuntu16:~$ st2 --debug apikey get foobar
2017-06-14 19:55:19,214  DEBUG - Using cached token from file "/home/ubuntu/.st2/token-testu"
# -------- begin 140133535286672 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.11.1' -H  'X-Auth-Token: 92fb784a9bf0462db72b097bbb9f7b81' http://127.0.0.1:9101/v1/apikeys/foobar
# -------- begin 140133535286672 response ----------
{
    "faultstring": "Unauthorized - ApiKey with key or id=foobar not found."
}
# -------- end 140133535286672 response ------------

Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 162, in get_resource_by_pk
    instance = self.manager.get_by_id(pk, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/models/core.py", line 39, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/models/core.py", line 204, in get_by_id
    self.handle_error(response)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/models/core.py", line 165, in handle_error
    response.raise_for_status()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 401 Client Error: Unauthorized
MESSAGE: Unauthorized - ApiKey with key or id=foobar not found. for url: http://127.0.0.1:9101/v1/apikeys/foobar
ERROR: 401 Client Error: Unauthorized
MESSAGE: Unauthorized - ApiKey with key or id=foobar not found. for url: http://127.0.0.1:9101/v1/apikeys/foobar

CLI settings:
----------------
Config file path: /home/ubuntu/.st2/config
Client settings:
----------------
ST2_BASE_URL: http://127.0.0.1
ST2_AUTH_URL: http://127.0.0.1:9100
ST2_API_URL: http://127.0.0.1:9101/v1
ST2_AUTH_TOKEN: 92fb784a9bf0462db72b097bbb9f7b81

Proxy settings:
---------------
HTTP_PROXY:
HTTPS_PROXY:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/shell.py", line 289, in run
    args.func(args)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 324, in run_and_print
    instance = self.run(args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 44, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 320, in run
    return self.get_resource_by_id(resource_id, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 176, in get_resource_by_id
    instance = self.get_resource_by_pk(pk=id, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 169, in get_resource_by_pk
    raise e
HTTPError: 401 Client Error: Unauthorized
MESSAGE: Unauthorized - ApiKey with key or id=foobar not found. for url: http://127.0.0.1:9101/v1/apikeys/foobar
```
```
ubuntu@ansible-st2-ubuntu16:~$ st2 apikey get foobar
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 162, in get_resource_by_pk
    instance = self.manager.get_by_id(pk, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/models/core.py", line 39, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/models/core.py", line 204, in get_by_id
    self.handle_error(response)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/models/core.py", line 165, in handle_error
    response.raise_for_status()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 401 Client Error: Unauthorized
MESSAGE: Unauthorized - ApiKey with key or id=foobar not found. for url: http://127.0.0.1:9101/v1/apikeys/foobar
ERROR: 401 Client Error: Unauthorized
MESSAGE: Unauthorized - ApiKey with key or id=foobar not found. for url: http://127.0.0.1:9101/v1/apikeys/foobar

ubuntu@ansible-st2-ubuntu16:~$ st2 --version
st2 2.2.1
```

**st2 2.3dev**

```
vagrant@u16:~$ st2 --debug apikey get foobar
2017-06-14 19:54:09,881  DEBUG - Using cached token from file "/home/vagrant/.st2/token-st2admin"
# -------- begin 140441537762768 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.14.2' -H  'X-Auth-Token: b8c7dd37c60744bdac6ec37e3df0cb51' http://127.0.0.1:9101/v1/apikeys/foobar
# -------- begin 140441537762768 response ----------
{
    "faultstring": "ApiKey matching foobar for reference and id not found."
}
# -------- end 140441537762768 response ------------

API Key "foobar" is not found.

CLI settings:
----------------
Config file path: /home/vagrant/.st2/config
Client settings:
----------------
ST2_BASE_URL: http://127.0.0.1
ST2_AUTH_URL: http://127.0.0.1:9100
ST2_API_URL: http://127.0.0.1:9101/v1
ST2_AUTH_TOKEN: b8c7dd37c60744bdac6ec37e3df0cb51

Proxy settings:
---------------
HTTP_PROXY:
HTTPS_PROXY:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/shell.py", line 298, in run
    args.func(args)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 331, in run_and_print
    raise OperationFailureException('Resource %s not found.' % resource_id)
OperationFailureException: Resource foobar not found.
```
```
vagrant@u16:~$ st2 apikey get foobar
API Key "foobar" is not found.

vagrant@u16:~$ st2 --version
st2 2.3dev
```

**Comment by humblearner** [comment] 2017-06-20 16:58
Closing for now, please open if reproducible.

**Closed by humblearner** 2017-06-20 16:58 UTC
Labels: status:to be verified
