### ISSUE TITLE
Getting error while creating restart service rule in Stackstorm

### ISSUE THREAD

**Issue by sanjeev02saraswat** [StackStorm/st2#5604] opened 2022-04-01 09:40 UTC
## SUMMARY

We tried to restart linux service using stackstorm and created linux.service. When we tried to run that getting below error.

**Error:**: Traceback (most recent call last):\n  File \"/tmp/6244491ccb55c0f4c7922066/service.py\", line 32, in <module>\n    from st2common.util.shell import quote_unix\nImportError: No module named st2common.util.shell

Command to restart service was: systemctl restart httpd.service

Please suggest what changes we need to do for this error.

### STACKSTORM VERSION

Paste the output of ``st2 --version``:

##### OS, environment, install method

Post what OS you are running this on, along with any other relevant information/

- e.g. Docker, Vagrant, Kubernetes, etc. Describe how you installed ST2
- e.g. one-line install, custom install, etc -->

## Steps to reproduce the problem

Show how to reproduce the problem, using a minimal test-case. Make sure to include any content
(pack content - workflows, actions, etc.) which are needed to reproduce the problem.

## Expected Results

What did you expect to happen when running the steps above?

## Actual Results

What happened? What output did you get?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by nzlosh** [comment] 2022-04-01 10:05
Duplicate of https://github.com/StackStorm/st2/issues/5004

**Closed by nzlosh** 2022-04-01 10:05 UTC

**Comment by sanjeev02saraswat** [comment] 2022-04-05 09:56
$ st2 --version
st2 3.6.0, on Python 3.6.8

Installed on Linux server and it was one line install.

**Comment by sanjeev02saraswat** [comment] 2022-04-07 09:59
@nzlosh  we look into the error 5004 , we still did not find any resolution regarding our issue. We are getting same error while running linux.service. Kindly provide any detail , what changes we should do for running this service. I have provided error logs below:
{
  "hostname**": {
    "stdout": "",
    "stderr": "Traceback (most recent call last):\n  File \"/tmp/6244491ccb55c0f4c7922066/service.py\", line 32, in <module>\n    from st2common.util.shell import quote_unix\nImportError: No module named st2common.util.shell",
    "return_code": 1,
    "succeeded": false,
    "failed": true
  }
}
