### ISSUE TITLE
Keystone backend not available on 0.13.x

### ISSUE THREAD

**Issue by Itxaka** [StackStorm/st2#1983] opened 2015-09-14 10:35 UTC
```
==> /var/log/st2/st2auth.log <==
    module = __import__(name, fromlist=fromlist)
  File "/usr/lib/python2.7/dist-packages/st2auth/controllers/root.py", line 19, in <module>
    class RootController(object):
  File "/usr/lib/python2.7/dist-packages/st2auth/controllers/root.py", line 20, in RootController
    tokens = auth.TokenController()
  File "/usr/lib/python2.7/dist-packages/st2auth/controllers/auth.py", line 39, in __init__
    self._auth_backend = get_backend_instance(name=cfg.CONF.auth.backend)
  File "/usr/lib/python2.7/dist-packages/st2auth/backends/__init__.py", line 42, in get_backend_instance
    raise ValueError('Invalid authentication backend specified: %s', name)
ValueError: ('Invalid authentication backend specified: %s', 'keystone')
```

This is due to `BACKEND_MODULES` on https://github.com/StackStorm/st2/blob/v0.13/st2auth/st2auth/backends/__init__.py not including keystone backend as an option.

**Comment by enykeev** [comment] 2016-11-18 07:22
As far as I understand, the issue is no longer valid due to auth backends being moved out to separate repos\packages.

For information on installing Keystone backend please refer to [Auth Backends](https://docs.stackstorm.com/authentication.html?highlight=keystone#auth-backends) documentation and [st2-auth-backend-keystone](https://github.com/StackStorm/st2-auth-backend-keystone) repo.

Closing.

**Closed by enykeev** 2016-11-18 07:22 UTC
