### ISSUE TITLE
Example.isprime required arg

### ISSUE THREAD

**Issue by Mierdin** [StackStorm/st2#3090] opened 2016-12-05 01:11 UTC
In the GUI (I am currently using BWC, and will verify if this is in the community edition as well) for the examples.isprime action, there is no field indicated as "required". However, if I just run the action without input, it justifiably raises an exception. Should properly indicate required input.

**Comment by enykeev** [comment] 2016-12-06 05:11
The problem is not that input is not indicated properly. It appears that after runner change (or even earlier), the `run` functions always get all the arguments even if they weren't provided during execution creation. So `value` is being supplied as `None` and doesn't default to `0`.

We need to find when the change had happened, asses how an attempt to change it back will impact compatibility, document the correct way of setting a default value on a python action and make sure our packs follow it.

**Comment by LindsayHill** [comment] 2017-12-14 01:55
@Mierdin looks like this is the same underlying issue as that one I noticed the other day here https://github.com/StackStorm/st2/issues/3906 - it seems that we now explicitly pass through `None` if an argument is not specified, rather than noting. Looks like it goes back > 1 yr, so I'm just going to put in a fix for this pack for now.

**Comment by LindsayHill** [comment] 2017-12-14 01:59
From a very cursory glance through some other Exchange packs, it looks like there are relatively few actions that have a combination of optional parameters with no defaults, AND code like this `def run(self, required_param, optional_param=some_default)`

**Closed** 2017-12-18 23:58 UTC
Labels: bug
