### ISSUE TITLE
Default values in pack config schema not being honored

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#3468] opened 2017-06-13 12:54 UTC
If a pack has a schema that declares a default value for a specific property and the property is absent in the config instance (`/opt/stackstorm/configs/<pack>.yaml`), then a python runner attempts to read this value from the config a `KeyError` is thrown instead of the default value being returned.

# Steps to reproduce
I've created a test pack that demonstrates this: https://github.com/nmaludy/stackstorm-testconfigdefault
```
st2 pack install https://github.com/nmaludy/stackstorm-testconfigdefault
st2 run testconfigdefault.get_config key='output'
```

# Output:
```
[root@stackstorm ~]# st2 run testconfigdefault.get_config key='output'
.
id: 593fdecfa814c06997fc8fd4
status: failed
parameters: 
  key: output
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/testconfigdefault/actions/get_config.py", line 11, in run
    return self.config[key]
KeyError: u'output'
"
  stdout: ''
```

# Expected output:
I expect to have the default value of 'json' from the schema be returned. Maybe i'm incorrect in my assumption?

**Comment by Kami** [comment] 2017-06-13 13:13
Which version of StackStorm are you running?

I believe it's related to an issue which has been fixed in v2.2.1 - https://github.com/StackStorm/st2/pull/3260

**Comment by nmaludy** [comment] 2017-06-13 13:15
```
[root@stackstorm ~]# st2 --version
st2 2.2.0
```

I'll try upgrading

**Comment by nmaludy** [comment] 2017-06-13 13:39
Same error with 2.2.1

```
[root@stackstorm ~]# st2 --version
st2 2.2.1
[root@stackstorm ~]# st2 run testconfigdefault.get_config key='output'
.
id: 593feb0da814c006059ee511
status: failed
parameters: 
  key: output
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/testconfigdefault/actions/get_config.py", line 11, in run
    return self.config[key]
KeyError: u'output'
"
  stdout: ''
```

**Comment by Kami** [comment] 2017-06-13 13:51
Thanks for testing with v2.2.1.

I was able to reproduce the issue. It's related to the config item not being required (`required: false`). We only set default values for items which are required.

I believe we had a special reason to do go with this behavior in the past (something with Mistral workflow and default parameter values, IIRC).

Simple solution is to change config item required attribute from false to true (it has no negative affect because item being required and having a default value is the same as not being required and not having a default value).

Having said that, I will dig in and think about it some more - maybe now it makes sense to also assign default values for config items which have `required: false`.

**Comment by nmaludy** [comment] 2017-06-13 13:55
@Kami that did work, thanks for the workaround and thanks for looking into this!

**Comment by Kami** [comment] 2017-06-13 14:39
After some more thinking about it, I don't think it should have any negative and breaking impact and #3468 should do the trick.

**Closed** 2017-06-13 16:13 UTC

**Comment by Sphinxs** [comment] 2019-12-20 02:53
Same problem. I found out that the `password` key had a `#` as part of the password, which turns the YAML to be not valid, but no errors are issued in the parsing, only where the keys are used, which causes a misundersnd, from my point of view, to debug.

**Comment by Kami** [comment] 2019-12-20 10:02
@Sphinxs can you please post config schema in question (and any actual values, masking / changing any sensitive ones) so we can try to reproduce the issue?

It could simply be that it's working as intended and ``#`` is being treated as comment.

**Comment by Sphinxs** [comment] 2019-12-20 13:42
I have fixed yesterday using quotation marks:

Before:

```yaml
---
host: 0.0.0.0
port: 9200
user: elastic
pass: #
use_ssl: false
```
After:

```yaml
---
host: 0.0.0.0
port: 9200
user: elastic
pass: '#'
use_ssl: false
```

**Comment by Kami** [comment] 2019-12-20 18:47
@Sphinxs Yes, for safety and explicitness reasons, you should always quote all the strings otherwise you will be up for more surprises (e.g. ``2.0`` will be parsed as a number and not a string, etc.).

In the example you posted, it behaves as expected.

In YAML, ``#`` is considered as a comment so it works as expected / designed and there is nothing we can (or should) do about it since then we would be changing YAML behavior...

**Comment by Sphinxs** [comment] 2019-12-20 18:50
Yeah, thanks. I was think that the YAMl could treat the # as a value, once this is asside the other two characters, but its imposslbe to do this once the # can be user !@# and it still a comment, my point it's kinda wtf, but...

**Comment by Kami** [comment] 2019-12-20 18:52
Yeah, YAML definitely has some "confusing" behavior so I always prefer to quote strings to avoid similar issues.
