### ISSUE TITLE
'maximum recursion depth exceeded' when st2auth is called (while login to webui)

### ISSUE THREAD

**Issue by daniilyar-confyrm** [StackStorm/st2#2819] opened 2016-07-19 21:54 UTC
I've set up an st2 stack on clean Ubuntu 14.04 LTS using this doc: https://docs.stackstorm.com/install/deb.html. All st2 components are deployed on same AWS EC2 instance.
But I am getting the 'maximum recursion depth exceeded' error when I try to login into webui. 

What exactly is happening for me:
1). I open webui, put login and password, then hit the 'Login' button.
2). Webui does the POST request to https://{{ host }}/auth/tokens URL.
3). This POST request is failing with 400 error code. Browser console logs the following error:

```
st2client.js:1031 POST https://stackstorm.dev.confyrm.com/auth/tokens 400 (Bad Request) xhrAdapter @ st2client.js:1031(anonymous function) @ st2client.js:1194dispatchRequest @ st2client.js:1190
```

4). Browser shows the following error message: https://gist.github.com/daniilyar-confyrm/986a97747589e75016acfa482435c44c

screenshot: http://imgur.com/Mda2K8z

5). If I try to make the same request with curl, I get the following error:

```
curl --insecure -i -XPOST  https://stackstorm.dev.confyrm.com/auth/tokens
```

```
 ....
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/log.py", line 154, in write
    self._logger._log(self._level, message, None)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 124, in print_exception
    _print(file, 'Traceback (most recent call last):')
  File "/usr/lib/python2.7/traceback.py", line 13, in _print
    file.write(str+terminator)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/log.py", line 154, in write
    self._logger._log(self._level, message, None)
  File "/usr/lib/python2.7/logging/__init__.py", line 1270, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1244, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 266, in __init__
    self.levelname = getLevelName(level)
  File "/usr/lib/python2.7/logging/__init__.py", line 167, in getLevelName
    return _levelNames.get(level, ("Level %s" % level))
RuntimeError: maximum recursion depth exceeded while getting the str of an object
</pre>
    </div>

    <b>Want to debug this request?</b>
    <div id="debug">
      You can <button onclick="debug_request(this)">
        repeat this request
      </button> with a Python debugger breakpoint.
    </div>

    <h2>WSGI Environment</h2>
    <div id="environ">
      <pre class="brush: python">{'CONTENT_LENGTH': '0',
 'HTTP_ACCEPT': '*/*',
 'HTTP_HOST': 'stackstorm.dev.confyrm.com,stackstorm.dev.confyrm.com',
 'HTTP_USER_AGENT': 'curl/7.35.0',
 'HTTP_X_FORWARDED_FOR': '10.144.101.18',
 'HTTP_X_REAL_IP': '10.144.101.18',
 'PATH_INFO': '/tokens',
 'QUERY_STRING': '',
 'RAW_URI': '/tokens',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '49499',
 'REQUEST_METHOD': 'POST',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '127.0.0.1',
 'SERVER_PORT': '9100',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'gunicorn/19.6.0',
 'gunicorn.socket': <eventlet.greenio.base.GreenSocket object at 0x7fc5d4c92310>,
 'pecan.recursive.script_name': '',
 'webob._parsed_post_vars': (MultiDict([]),
                             <_io.BytesIO object at 0x7fc5d08d8830>),
 'webob._parsed_query_vars': (GET([]), ''),
 'webob.adhoc_attrs': {'context': {},
                       'pecan': {'content_type': 'application/json',
                                 'extension': None,
                                 'routing_path': '/tokens'}},
 'webob.is_body_seekable': True,
 'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7fc5d0856c90>,
 'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
 'wsgi.input': <_io.BytesIO object at 0x7fc5d08d8830>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}</pre>
    </div>
  </div>
 </body>
</html>
```

**Comment by daniilyar-confyrm** [comment] 2016-07-19 22:14
Update: I am getting the same error if I install st2 via official Ansible playbook (https://github.com/StackStorm/ansible-st2) at clean Ubuntu 14.04 EC2 instance.

Playbook is failing with following error on 'run smoke tests' step: 
```
TASK: [st2smoketests | get authentication token] ****************************** 
Wednesday 20 July 2016  01:11:54 +0300 (0:00:01.433)       0:01:11.639 ******** 
failed: [10.145.40.25] => {"changed": true, "cmd": ["st2", "auth", "testu", "-p", "testp", "-t"], "delta": "0:00:00.262477", "end": "2016-07-19 22:11:56.212426", "rc": 1, "start": "2016-07-19 22:11:55.949949", "warnings": []}
stdout: ERROR: 400 Client Error: Bad Request
Unable to retrieve detailed message from the HTTP response. Expecting value: line 1 column 1 (char 0)
 for url: http://127.0.0.1:9100/tokens

FATAL: all hosts have already failed -- aborting
```

**Comment by lakshmi-kannan** [comment] 2016-07-21 18:46
@daniilyar-confyrm Interesting report and one we haven't seen so far. Please answer the following questions:

1. What is the version of st2 that is installed? st2 --version or sudo apt-cache policy st2.
2. Is ufw running on box? Did you try disabling it? 
3. Is st2auth process running on the st2 box? ps auxww | grep st2auth
4. Have you tailed /var/log/st2/st2auth.log to see if there are any errors?

**Comment by daniilyar-confyrm** [comment] 2016-07-25 09:48
1. St2 version 1.5.1
2. ufw 0.34~rc-0ubuntu2 version is running on the host, disabling it doesn't help.
3. st2auth is running on the same box, as st2:
```
# ps auxww | grep st2auth
st2      10758  0.0  0.6  81112 24320 ?        Ss   Jul20   0:34 /opt/stackstorm/st2/bin/python /opt/stackstorm/st2/bin/gunicorn_pecan /opt/stackstorm/st2/lib/python2.7/site-packages/st2auth/gunicorn_config.py -k eventlet -b 127.0.0.1:9100 --workers 1 --threads 1 --graceful-timeout 10 --timeout 30
st2      10959  0.0  0.9 128500 38648 ?        S    Jul20   1:09 /opt/stackstorm/st2/bin/python /opt/stackstorm/st2/bin/gunicorn_pecan /opt/stackstorm/st2/lib/python2.7/site-packages/st2auth/gunicorn_config.py -k eventlet -b 127.0.0.1:9100 --workers 1 --threads 1 --graceful-timeout 10 --timeout 30
root     27367  0.0  0.0  10464   932 pts/16   S+   09:46   0:00 grep --color=auto st2auth
```
4. `/var/log/st2/st2auth.log` contains only INFO messages like below:
```
2016-07-25 06:54:38,428 140299359636048 INFO misc [-] Re-opening log file "/var/log/st2/st2auth.log" with mode "a"
```

**Comment by daniilyar-confyrm** [comment] 2016-07-25 09:51
After I dockerized Nginx, Rabbit, Mongo and Postgres, and refactored the st2 Ansible playbook to match our needs, I was able to spin up a working st2 1.5.1, which doesn't show the same issue on the same box. Not sure what was the difference which helped in my case. But I will try to find the exact reason of this error and share my thoughts on that this week.

**Comment by Kami** [comment] 2016-07-25 09:58
Like @lakshmi-kannan has said, this is really a weird issue and we haven't seen one like it before.

It almost looks like it's using some 3rd party `logging` package or some other `logging` package is in st2 `PYTHONPATH` which is causing issues. This shouldn't happen thought since all the `st2` components are installed inside a purpose built virtual environment.

Anyway, glad to hear that it's working now. We will still keep an eye on similar issues in the future though.

**Comment by enykeev** [comment] 2016-11-22 07:25
As previous commenters pointed out, the issue is highly unusual and no actionable steps can be done at that point. Going to close it. Please reopen if the issue reappear.

**Closed by enykeev** 2016-11-22 07:25 UTC
Labels: status:need more info
