### ISSUE TITLE
Stackstorm pack installation behind proxy

### ISSUE THREAD

**Issue by sumeshkanayi** [StackStorm/st2#2867] opened 2016-08-13 01:26 UTC
Hi I have a machine which is not allowed to use github.com and is blocked through a proxy.Is there a way i can install integration packs on it?

**Comment by LindsayHill** [comment] 2016-08-13 01:34
Try this: https://docs.stackstorm.com/proxy.html

**Comment by sumeshkanayi** [comment] 2016-08-13 02:16
Woww It was quick. I tried it but my proxy doesn't allow me to clone github at all,but i am able to zip the repository. In this case is there way i can install packs on my stackstorm instance?

**Comment by Kami** [comment] 2016-08-13 07:15
@sumeshkanayi Yeah, you just need to make sure the actual pack directory ends up in `/opt/stackstorm/packs/` directory and after that you need to run `st2ctl reload --register-all` to register the content.

You can deploy it any way you like (scp, sftp, etc., but deploying via git is preferred in infrastructure as code environments - you can use your corporate git server to version control your StackStorm packs or similar).

**Comment by sumeshkanayi** [comment] 2016-08-13 13:40
Thanks @Kami

 extracted and copied the pack (jenkins) to /opt/stackstorm/packs

later i ran the below command and ended up in error 

 st2 run packs.setup_virtualenv packs=jenkins

the error message is same as mentioned in https://github.com/StackStorm/st2workroom/issues/351
----------------------------------------------------

)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/virtualen
vs.py", line 188, in install_requirement
    (requirement, stdout))
Exception: Failed to install requirement "six>=1.9.0,<2.0": Collecting six<2.0,>
=1.9.0
---------------------
/opt/stackstorm/st2/bin/pip show six  command says that the six is installed as you can see below

 Metadata-Version: 2.0
Name: six
Version: 1.10.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
Installer: pip
License: MIT
Location: /opt/stackstorm/st2/lib/python2.7/site-packages
Requires:
Classifiers:
  Programming Language :: Python :: 2
  Programming Language :: Python :: 3
  Intended Audience :: Developers
  License :: OSI Approved :: MIT License
  Topic :: Software Development :: Libraries
  Topic :: Utilities

**Comment by Kami** [comment] 2016-08-14 10:19
@sumeshkanayi Packs use different virtual environment than the one used by StackStorm components - each pack uses a separate isolated virtual environment (`/opt/stackstorm/virtualenvs/jenkins` in your case).

One option is to some how get six and wheel for other dependencies inside your server and then do something like `/opt/stackstorm/virtualenvs/jenkins/bin/pip install --wheel-dir=path to wheel dir /opt/stackstorm/packs/jenkins/requirements.txt`.

On a related note, did you try specifying env=HTTP_PROXY=yourproxy parameter when running `packs.setup_virtualenv` command? (the root cause still is the proxy and not being able to access Github and PyPi to download dependencies).

**Comment by sumeshkanayi** [comment] 2016-08-14 18:34
Excellent ..Thanks so much for this. I installed six and wheel with the below commands (With proxy set) and did a st2 run packs.load register=all .Wored fine without any issues.. Thanks a lot again
/opt/stackstorm/virtualenvs/jenkins/bin/pip install six -r /opt/stackstorm/packs/jenkins/requirements.txt
/opt/stackstorm/virtualenvs/jenkins/bin/pip install wheel -r /opt/stackstorm/packs/jenkins/requirements.txt

**Comment by Kami** [comment] 2016-08-14 20:12
Great to hear that this worked :)

We should also update our docs to document this work-around.

**Comment by Kami** [comment] 2016-09-02 13:44
This has been resolved, closing.

**Closed by Kami** 2016-09-02 13:44 UTC
