### ISSUE TITLE
Version 2.2.0 is very unstable

### ISSUE THREAD

**Issue by pietervogelaar** [StackStorm/st2#3299] opened 2017-03-22 10:01 UTC
I upgraded StackStorm a few weeks ago from version 2.1.1 to version 2.2.0, but I'm at the point of reverting back to version 2.1.1.

StackStorm seems very unstable. CPU usage can suddenly be very high when StackStorm is doing no executions. Since yesterday commands from Slack executed an action in StackStorm, but chatops.post_result wasn't triggered, so chatops is broken. And today a rule that must trigger a workflow doesn't work anymore.

What's going on?!

**Comment by Kami** [comment] 2017-03-22 14:14
Thanks for reporting this.

From top of my head, I can't think of any direct change we made which could have an effect on this.

The only thing I could think of is an issue because of the dependencies upgrade - we upgraded some libraries we depend on (and the only one being potentially problematic is paramiko used for remote runner actions, but this would potentially only affect remote runner actions).

Having said that, without any additional and more detailed information it's just speculation and we can't help.

To get a better understand of what is going on, we would at the very least need:

1. Actual full system snapshop when issues happen (memory usage, CPU usage, syscalls)
2. Logs of all the corresponding services
3. Idea of what kind of workflows, etc you are running
4. Which process is causing high CPU usage? actionrunner? something else?

Ideally you could provide output from something like Sysdig (http://www.sysdig.org/) or at the very least, strace the offending process.

As far as the rule goes - this looks like an unrelated thing and we also can't know what is going on without having all the information (logs, which rules are in place, etc.).

**Comment by pietervogelaar** [comment] 2017-03-24 13:49
It seems it's just isolated to Mistral. With strace I was able to figure out that a core.remote action was trying to connect with SSH to a Solaris server. But the SSH connection didn't gave a timeout. It completely hanged the mistral task into running state and I was not be able to cancel it. Even with all the instructions on this page https://stackstorm.reamaze.com/kb/mistral/mistral-workflow-stuck-in-running-state. The resource usage on the servers was just crazy. I had to completely redeploy the rabbitmq, mongodb and postgres server to get a nice running StackStorm environment again.

**Comment by pietervogelaar** [comment] 2017-03-24 13:50
I converted the mistral workflows to action chains which seem much more robust.

**Comment by LindsayHill** [comment] 2017-03-24 15:22
> The resource usage on the servers was just crazy

@pietervogelaar Could you provide some more stats on what you were seeing? memory usage, CPU, which processes were consuming resources, etc?

**Comment by pietervogelaar** [comment] 2017-03-27 07:00
![stackstorm-crash](https://cloud.githubusercontent.com/assets/1067483/24344447/dc20e56a-12cb-11e7-8fb4-76b713f9bd74.gif)

**Comment by bigmstone** [comment] 2017-03-27 20:01
@pietervogelaar Do you have a good way to reproduce this? You mentioned ssh to a non-existent or down box - is that how you're able to reproduce it?

**Comment by pietervogelaar** [comment] 2017-03-28 08:59
The core.remote action was used as task in a Mistral workflow. It connected to a Solaris server that runs Oracle. They said they fased out the this server, but when everything hang I tried SSH manually. What I found was that the server was not yet destroyed, but was still pingable. However when I tried to login with SSH, my prompt was just busy/waiting. I didn't get a fail, but I also didn't get logged in. With strace on the st2actionrunner process that caused a high load, I saw a recv failed about every 10 seconds. The message was something like "The resource is temporarily unavailable". So I think the process was trying it over and over again which causes the task to keep running and never end. And maybe because the connections where hanging and new connections were opened, load was stacking up.

**Comment by LindsayHill** [comment] 2017-06-19 18:34
In version 2.3 we've made some changes to the Mistral workflow querier processes, in https://github.com/StackStorm/st2/pull/3413 and https://github.com/StackStorm/st2/pull/3420

I suspect that some of the issues you were seeing are related to those. Will be interesting to see if problems persist with v2.3.

**Closed** 2018-03-20 00:02 UTC
Labels: performance, status:to be verified
