### ISSUE TITLE
Service files for st2actionrunner are deleted on restart

### ISSUE THREAD

**Issue by cbrenton** [StackStorm/st2#2756] opened 2016-06-17 22:23 UTC
When I restart my machine, I am unable to start the st2actionrunner service. Further investigation reveals that the files in `/usr/lib/systemd/system/st2actionrunner*.service` are missing. Fixing this requires running `yum reinstall st2`. This happens consistently when restarting this machine (CentOS 7).

**Comment by Kami** [comment] 2016-06-18 15:42
Thanks for the report.

How did you install StackStorm (AIO or packages)?

IIRC, similar issue was reported recently when installing packages on top of deprecated AIO based installation. AIO based installation has been deprecated and packages should always be used on a clear / fresh server.

If you experienced this issue when using package based installation on a fresh server, let us know and provide as much details as possible and we will dig in.

**Comment by DoriftoShoes** [comment] 2016-06-21 21:15
I've been unable to repro this issue.  @cbrenton What installation method did you use?  Was this a fresh install with the new packages?

**Comment by Kami** [comment] 2016-06-22 05:46
To clarify it again - user reported the same issue in the past when they installed new packages over AIO installation.

That's a expected since we don't support that use case (AIO has been deprecated you need to migrate content and install packages on a new server). The problem is that with AIO puppet will periodically run and remove files, etc.

**Comment by cbrenton** [comment] 2016-06-23 22:56
I believe this instance was installed using the AIO installer. I will update our install process accordingly.

**Comment by stevemuskiewicz** [comment] 2016-06-28 21:32
I also just saw this same issue (also on CentOS 7.x) and originally installed from packages, not AIO.  So I don't think that is the root cause of the problem.

(Note that I previously saw something similar when running a VM which was using networked storage that had timed out.  However this instance of the VM is using local storage on my ESXi server and the problem is still happening which makes me suspicious of what's causing it)

Let me know if I can provide more info.

**Comment by cbrenton** [comment] 2016-06-29 21:38
On further investigation, I realized that the box where this issue is happening was not using the AIO installer - it was using a slightly modified version of the [st2bootstrap script](https://github.com/StackStorm/st2-packages/blob/master/scripts/st2bootstrap-el7.sh). The box with the issue doesn't have puppet installed at all. This is likely unrelated to the AIO installer.

**Comment by LindsayHill** [comment] 2016-09-15 15:47
Looks like we've tracked this down at last, and fixes have been merged https://github.com/StackStorm/st2/pull/2898

New patches will ship shortly, or you can manually apply those changes to your logrotate config.

**Closed by LindsayHill** 2016-09-15 15:47 UTC
