### ISSUE TITLE
ImportError: No module named 'inspect' in ActionRunner

### ISSUE THREAD

**Issue by dove-young** [StackStorm/st2#4931] opened 2020-05-01 08:44 UTC
## SUMMARY

I rebuild StackStorm docker images based on RedHat UBI image.  It runs well in OpenShift. 

But when I access to the `st2` client and run some acitons, it always failed at 

```
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 19, in <module>
    from cryptography.utils import CryptographyDeprecationWarning
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/cryptography/utils.py", line 9, in <module>
    import inspect
ImportError: No module named 'inspect'
```

Provide a quick summary of your bug report.

### STACKSTORM VERSION

Paste the output of ``st2 --version``:   

st2 3.2.0, on Python 2.7.5

##### OS, environment, install method

Post what OS you are running this on, along with any other relevant information/

Docker - based on RedHat UBI 7

- e.g. Docker, Vagrant, Kubernetes, etc. Describe how you installed ST2
- e.g. one-line install, custom install, etc -->

## Steps to reproduce the problem

Show how to reproduce the problem, using a minimal test-case. Make sure to include any content
(pack content - workflows, actions, etc.) which are needed to reproduce the problem.

- oc rsh -n stackstorm stackstorm-st2client-6d4f684cdb-w4rp2
- /opt/stackstorm/st2/bin/python  -m inspect  /usr/bin/st2 run cem_ibm.cem action=find obj_type=incidents filter="priority < 2 and state != 'closed'"

## Expected Results

What did you expect to happen when running the steps above?

## Actual Results

```
> /opt/stackstorm/st2/lib/python2.7/site-packages/st2client/formatters/execution.py(126)format()->'\x1b[94mid\x... stdout: \'\''
-> return result
(Pdb) n
id: 5eabde592db50c1743a58a6e
action.ref: cem_ibm.cem
context.user: st2admin
parameters:
  action: find
  filter: priority < 2 and state != 'closed'
  obj_type: incidents
status: failed
start_timestamp: Fri, 01 May 2020 08:31:21 UTC
end_timestamp: Fri, 01 May 2020 08:31:23 UTC
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 19, in <module>
    from cryptography.utils import CryptographyDeprecationWarning
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/cryptography/utils.py", line 9, in <module>
    import inspect
ImportError: No module named 'inspect'
"
  stdout: ''
SystemExit: SystemExit(1,)
> /usr/bin/st2(10)<module>()
-> sys.exit(main())
(Pdb)
```

What happened? What output did you get?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by dove-young** [comment] 2020-05-01 08:47
Finally it traced to line 126 of  https://github.com/StackStorm/st2/blob/master/st2client/st2client/formatters/execution.py

`break /opt/stackstorm/st2/lib/python2.7/site-packages/st2client/formatters/execution.py:122`

```
> /opt/stackstorm/st2/lib/python2.7/site-packages/st2client/formatters/execution.py(126)format()
-> return result
(Pdb) s
--Return--
> /opt/stackstorm/st2/lib/python2.7/site-packages/st2client/formatters/execution.py(126)format()->'\x1b[94mid\x... stdout: \'\''
--> return result
(Pdb) n
id: 5eabde592db50c1743a58a6e
action.ref: cem_ibm.cem
context.user: st2admin
parameters:
  action: find
  filter: priority < 2 and state != 'closed'
  obj_type: incidents
status: failed
start_timestamp: Fri, 01 May 2020 08:31:21 UTC
end_timestamp: Fri, 01 May 2020 08:31:23 UTC
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 19, in <module>
    from cryptography.utils import CryptographyDeprecationWarning
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/cryptography/utils.py", line 9, in <module>
    import inspect
ImportError: No module named 'inspect'
"
  stdout: ''
SystemExit: SystemExit(1,)
> /usr/bin/st2(10)<module>()
-> sys.exit(main())
(Pdb)
```

It is called at lien 380 of https://github.com/StackStorm/st2/blob/master/st2client/st2client/commands/action.py

```
def _run_and_print_child_task_list(self, execution, args, **kwargs):
        action_exec_mgr = self.app.client.managers['Execution']

        instance = execution
        options = {'attributes': ['id', 'action.ref', 'parameters', 'status', 'start_timestamp',
                                  'end_timestamp']}
        options['json'] = args.json
        options['attribute_transform_functions'] = self.attribute_transform_functions
-->   formatter = execution_formatter.ExecutionResult


```

**Comment by dove-young** [comment] 2020-07-22 10:16
still not fixed

**Comment by yypptest** [comment] 2020-07-22 10:34
have the similar issue

**Comment by yypptest** [comment] 2020-07-22 10:37
same issue here

**Comment by yypptest** [comment] 2020-07-22 11:02
this  is a test

**Comment by yypptest** [comment] 2020-07-22 11:07
I have the issue here

**Comment by yypptest** [comment] 2020-07-22 11:10
run vmstat on the box

**Comment by armab** [comment] 2020-07-22 11:17
Thanks for the report.
We couldn't see this error on StackStorm supported OS platforms which are `CentOS/RHEL 7/8`, `Ubuntu 16.04/18.04 LTS`.

If you have any ways to help reproducing this for someone else, - please provide more context.

**Comment by blag** [comment] 2021-06-02 20:08
I'm going to close this issue since it hasn't been updated in over a year and we don't support that OS.

If you can give us more information to help debug it, or if the problem still appears with StackStorm v3.4, please feel free to drop a comment here and we can reopen this issue. Thanks!

**Closed by blag** 2021-06-02 20:08 UTC
Labels: status:need more info
